'use client'

import { useSearchParams } from 'next/navigation'
import ServiceProductPage from '../ServiceProductPage'
import { servicesData } from '@/data/servicesData'

// Industry-specific content for Academic CV Writing
const industrySpecificContent = {
  'construction-industry': {
    industrySubtitle: 'For Academic & Research Professionals',
    description: `<strong style="color: #2563eb;">Build scholarly foundations for construction academia! Let our Academic CV Writing service construct your path to prestigious academic and research positions! 🏗️🎓</strong><br/><br/>Our construction-focused writers craft comprehensive academic CVs for researchers, professors, and industry academics—showcasing technical expertise and scholarly achievements. 🚧📚 Academic blueprints for construction excellence.`,
    detailedDescription: `Academic careers in construction, civil engineering, and architecture require CVs that demonstrate both scholarly achievements and industry expertise. Our specialized writers create comprehensive academic CVs that highlight your research publications, conference presentations, grant funding, teaching experience, and professional practice achievements in construction-related fields.<br/><br/>Whether you're pursuing academic positions in Civil Engineering, Construction Management, Architecture, or Applied Engineering Research, our academic CVs showcase your research contributions to construction technology, sustainable building practices, project management methodologies, or structural engineering innovations. We highlight your peer-reviewed publications, research grants, conference presentations, and industry collaborations.<br/><br/>Our construction academic CVs emphasize your dual expertise in scholarly research and practical construction experience, positioning you as a bridge between academic knowledge and industry application. Perfect for faculty positions, research roles, or industry-academic partnerships, we showcase your contribution to advancing construction knowledge through rigorous academic research and practical implementation.`,
  },
  'energy-oil-gas': {
    industrySubtitle: 'For Energy, Oil & Gas Professionals',
    description: `<strong style="color: #2563eb;">Power your academic career with scholarly precision! Let our Academic CV Writing service fuel your path to energy sector research and academic excellence! ⚡🛢️</strong><br/><br/>Our energy-focused writers create dynamic academic CVs for researchers, professors, and industry scholars—showcasing technical expertise and research achievements. 🏭🎓 Academic energy for scholarly advancement.`,
    detailedDescription: `Academic careers in energy, petroleum engineering, and renewable energy require CVs that demonstrate cutting-edge research and industry insight. Our specialized writers create comprehensive academic CVs highlighting your research in energy systems, petroleum geology, renewable energy technologies, or environmental energy studies.<br/><br/>Whether pursuing positions in Petroleum Engineering academia, Energy Policy Research, Environmental Engineering, or Renewable Energy Studies, our academic CVs showcase your research publications, grant funding, industry partnerships, and contribution to energy sector knowledge advancement.<br/><br/>Our energy academic CVs emphasize your expertise in both theoretical research and practical energy applications, positioning you as a leader in academic-industry collaboration and energy innovation research.`,
  },
  'tech-it': {
    industrySubtitle: 'For Technology & IT Professionals',
    description: `<strong style="color: #2563eb;">Debug your academic potential with precision-coded scholarly CVs! Let our Academic CV Writing service program your path to technology research excellence! 💻🚀</strong><br/><br/>Our tech-savvy writers develop cutting-edge academic CVs for computer science researchers, IT academics, and technology scholars—showcasing research innovation and technical expertise. 🔧🎓 Digital scholarship engineered for academic success.`,
    detailedDescription: `Academic careers in computer science, information technology, and digital innovation require CVs that demonstrate both technical expertise and scholarly rigor. Our specialized writers create comprehensive academic CVs highlighting your research in artificial intelligence, cybersecurity, data science, software engineering, or human-computer interaction.<br/><br/>Whether pursuing faculty positions in Computer Science, Information Systems Research, or Digital Innovation Studies, our academic CVs showcase your peer-reviewed publications, research grants, open-source contributions, conference presentations, and collaboration with industry technology leaders.<br/><br/>Our technology academic CVs emphasize your ability to conduct rigorous research while maintaining relevance to rapidly evolving technology landscapes, positioning you as a bridge between academic computer science research and practical technology innovation.`,
  },
  'healthcare-pharma': {
    industrySubtitle: 'For Healthcare & Pharmaceutical Professionals',
    description: `<strong style="color: #2563eb;">Prescribe academic excellence for healthcare scholarship! Let our Academic CV Writing service diagnose your path to medical and pharmaceutical research positions! 🏥💊</strong><br/><br/>Our healthcare-focused writers create professional academic CVs for medical researchers, pharmaceutical scientists, and healthcare academics—showcasing clinical expertise and scholarly achievements. 🩺🎓 Medical scholarship for healthcare advancement.`,
    detailedDescription: `Academic careers in medicine, pharmaceutical sciences, and health research require CVs that demonstrate clinical competency, research excellence, and commitment to advancing healthcare knowledge. Our specialized writers create comprehensive academic CVs highlighting your clinical research, pharmaceutical development work, medical publications, and healthcare innovation contributions.<br/><br/>Whether pursuing positions in Medical School Faculty, Pharmaceutical Research, Public Health Academia, or Clinical Research, our academic CVs showcase your peer-reviewed medical publications, research grants, clinical trial leadership, teaching experience, and contribution to medical knowledge advancement.<br/><br/>Our healthcare academic CVs emphasize your ability to translate clinical experience into scholarly research, positioning you as a leader in evidence-based medicine and healthcare innovation research.`,
  },
  'banking-financial-services-insurance': {
    industrySubtitle: 'For Banking, Financial Services & Insurance Professionals',
    description: `<strong style="color: #2563eb;">Invest in academic excellence with sophisticated scholarly CVs! Let our Academic CV Writing service calculate your path to finance and economics research positions! 💰📈</strong><br/><br/>Our finance-focused writers create sophisticated academic CVs for economics researchers, finance professors, and industry academics—showcasing analytical expertise and scholarly achievements. 🏦🎓 Financial scholarship for academic investment.`,
    detailedDescription: `Academic careers in finance, economics, and business require CVs that demonstrate both theoretical knowledge and practical market insight. Our specialized writers create comprehensive academic CVs highlighting your research in financial markets, economic theory, risk management, or behavioral finance.<br/><br/>Whether pursuing positions in Business School Faculty, Economics Research, or Financial Policy Academia, our academic CVs showcase your peer-reviewed publications, research grants, industry consulting experience, conference presentations, and contribution to financial knowledge advancement.<br/><br/>Our finance academic CVs emphasize your ability to conduct rigorous economic research while maintaining relevance to real-world financial markets, positioning you as a bridge between academic theory and practical financial application.`,
  },
  'sales-marketing': {
    industrySubtitle: 'For Sales & Marketing Professionals',
    description: `<strong style="color: #2563eb;">Market your scholarly potential with persuasive academic CVs! Let our Academic CV Writing service sell your expertise for marketing and business research excellence! 📊🎯</strong><br/><br/>Our results-driven writers create compelling academic CVs for marketing researchers, business professors, and commercial academics—showcasing research achievements and market expertise. 📈🎓 Academic marketing for scholarly persuasion.`,
    detailedDescription: `Academic careers in marketing, consumer behavior, and business studies require CVs that demonstrate both scholarly rigor and commercial insight. Our specialized writers create comprehensive academic CVs highlighting your research in consumer psychology, digital marketing, brand management, or business strategy.<br/><br/>Whether pursuing positions in Business School Marketing Faculty, Consumer Research, or Commercial Strategy Academia, our academic CVs showcase your peer-reviewed publications, research grants, industry partnerships, and contribution to marketing knowledge advancement.<br/><br/>Our marketing academic CVs emphasize your ability to conduct rigorous research while maintaining relevance to evolving commercial landscapes, positioning you as a leader in academic-industry collaboration and marketing innovation research.`,
  },
  'engineering-manufacturing': {
    industrySubtitle: 'For Engineering & Manufacturing Professionals',
    description: `<strong style="color: #2563eb;">Engineer academic excellence with precision-crafted scholarly CVs! Let our Academic CV Writing service manufacture your path to engineering research positions! ⚙️🏭</strong><br/><br/>Our technical writers create robust academic CVs for engineering researchers, manufacturing academics, and technical scholars—showcasing research expertise and innovation potential. 🔧🎓 Engineering scholarship for academic advancement.`,
    detailedDescription: `Academic careers in engineering and manufacturing require CVs that demonstrate both technical expertise and research innovation. Our specialized writers create comprehensive academic CVs highlighting your research in mechanical engineering, industrial processes, manufacturing systems, or engineering management.<br/><br/>Whether pursuing positions in Engineering Faculty, Manufacturing Research, or Applied Technology Academia, our academic CVs showcase your peer-reviewed publications, research grants, industry collaborations, patent applications, and contribution to engineering knowledge advancement.<br/><br/>Our engineering academic CVs emphasize your ability to conduct rigorous research while addressing real-world engineering challenges, positioning you as a leader in translating academic research into practical engineering solutions.`,
  },
  'strategy-consulting': {
    industrySubtitle: 'For Strategy & Consulting Professionals',
    description: `<strong style="color: #2563eb;">Strategize academic impact with analytically precise scholarly CVs! Let our Academic CV Writing service consult on your path to business strategy research excellence! 🎯📊</strong><br/><br/>Our strategy-focused writers create analytical academic CVs for strategy researchers, consulting academics, and business scholars—showcasing research expertise and strategic insight. 📈🎓 Strategic scholarship for academic consulting.`,
    detailedDescription: `Academic careers in strategy, management consulting, and organizational studies require CVs that demonstrate both analytical rigor and practical strategy insight. Our specialized writers create comprehensive academic CVs highlighting your research in strategic management, organizational behavior, consulting methodologies, or business transformation.<br/><br/>Whether pursuing positions in Strategy Faculty, Management Research, or Organizational Studies Academia, our academic CVs showcase your peer-reviewed publications, research grants, consulting experience, case study development, and contribution to strategic management knowledge.<br/><br/>Our strategy academic CVs emphasize your ability to conduct rigorous research while addressing real-world strategic challenges, positioning you as a bridge between academic strategy theory and practical consulting application.`,
  },
  'logistics-supply-chain': {
    industrySubtitle: 'For Logistics & Supply Chain Professionals',
    description: `<strong style="color: #2563eb;">Deliver academic excellence with operationally optimized scholarly CVs! Let our Academic CV Writing service optimize your path to supply chain research positions! 🚚📦</strong><br/><br/>Our operations-focused writers create efficient academic CVs for logistics researchers, supply chain academics, and operations scholars—showcasing research expertise and operational insight. ⚡🎓 Academic operations for scholarly optimization.`,
    detailedDescription: `Academic careers in logistics, supply chain management, and operations research require CVs that demonstrate both analytical rigor and operational expertise. Our specialized writers create comprehensive academic CVs highlighting your research in supply chain optimization, logistics systems, operations management, or global trade.<br/><br/>Whether pursuing positions in Operations Faculty, Supply Chain Research, or Logistics Academia, our academic CVs showcase your peer-reviewed publications, research grants, industry partnerships, and contribution to operations management knowledge advancement.<br/><br/>Our logistics academic CVs emphasize your ability to conduct rigorous research while addressing real-world supply chain challenges, positioning you as a leader in translating academic research into practical operational solutions.`,
  },
  'hospitality-tourism': {
    industrySubtitle: 'For Hospitality & Tourism Professionals',
    description: `<strong style="color: #2563eb;">Create exceptional academic journeys with scholarly CVs! Let our Academic CV Writing service host your path to hospitality and tourism research excellence! 🏨✈️</strong><br/><br/>Our service-focused writers create welcoming academic CVs for hospitality researchers, tourism academics, and service scholars—showcasing research expertise and industry insight. 🌟🎓 Academic hospitality for scholarly distinction.`,
    detailedDescription: `Academic careers in hospitality management, tourism studies, and service research require CVs that demonstrate both scholarly rigor and industry understanding. Our specialized writers create comprehensive academic CVs highlighting your research in hospitality operations, tourism economics, cultural studies, or service management.<br/><br/>Whether pursuing positions in Hospitality Faculty, Tourism Research, or Service Studies Academia, our academic CVs showcase your peer-reviewed publications, research grants, industry collaborations, and contribution to hospitality and tourism knowledge advancement.<br/><br/>Our hospitality academic CVs emphasize your ability to conduct rigorous research while maintaining relevance to evolving hospitality and tourism industries, positioning you as a bridge between academic research and practical service excellence.`,
  },
  'media-entertainment': {
    industrySubtitle: 'For Media & Entertainment Professionals',
    description: `<strong style="color: #2563eb;">Direct your academic spotlight with creatively compelling scholarly CVs! Let our Academic CV Writing service produce award-worthy applications for media research excellence! 🎬🎭</strong><br/><br/>Our creative writers craft captivating academic CVs for media researchers, entertainment academics, and creative scholars—showcasing research achievements and artistic insight. 🎨🎓 Creative scholarship for academic storytelling.`,
    detailedDescription: `Academic careers in media studies, entertainment research, and creative arts require CVs that demonstrate both scholarly rigor and creative expertise. Our specialized writers create comprehensive academic CVs highlighting your research in media theory, digital communications, entertainment industry studies, or creative practice research.<br/><br/>Whether pursuing positions in Media Studies Faculty, Entertainment Research, or Creative Arts Academia, our academic CVs showcase your peer-reviewed publications, research grants, creative works, exhibitions, and contribution to media and entertainment knowledge advancement.<br/><br/>Our media academic CVs emphasize your ability to conduct rigorous research while engaging with contemporary media and entertainment landscapes, positioning you as a leader in academic-creative collaboration and media innovation research.`,
  },
  'human-resources': {
    industrySubtitle: 'For Human Resources Professionals',
    description: `<strong style="color: #2563eb;">Develop exceptional academic narratives with strategic scholarly CVs! Let our Academic CV Writing service recruit success for your HR research journey! 👥💼</strong><br/><br/>Our people-focused writers create strategic academic CVs for HR researchers, organizational academics, and management scholars—showcasing research expertise and people development insight. 🎯🎓 Academic people strategy for scholarly advancement.`,
    detailedDescription: `Academic careers in human resources, organizational psychology, and management studies require CVs that demonstrate both research excellence and practical people management understanding. Our specialized writers create comprehensive academic CVs highlighting your research in organizational behavior, talent management, leadership studies, or workplace psychology.<br/><br/>Whether pursuing positions in HR Faculty, Organizational Research, or Management Studies Academia, our academic CVs showcase your peer-reviewed publications, research grants, consulting experience, and contribution to human resources knowledge advancement.<br/><br/>Our HR academic CVs emphasize your ability to conduct rigorous research while addressing real-world organizational challenges, positioning you as a bridge between academic theory and practical people management solutions.`,
  },
  'fmcg-retail': {
    industrySubtitle: 'For FMCG & Retail Professionals',
    description: `<strong style="color: #2563eb;">Stock your academic future with market-ready scholarly CVs! Let our Academic CV Writing service retail your potential for consumer research excellence! 🛒🏪</strong><br/><br/>Our consumer-focused writers create compelling academic CVs for retail researchers, consumer academics, and marketing scholars—showcasing research achievements and commercial insight. 📊🎓 Academic consumer intelligence for scholarly marketing.`,
    detailedDescription: `Academic careers in retail studies, consumer behavior, and commercial research require CVs that demonstrate both scholarly rigor and market understanding. Our specialized writers create comprehensive academic CVs highlighting your research in consumer psychology, retail operations, brand management, or commercial strategy.<br/><br/>Whether pursuing positions in Marketing Faculty, Consumer Research, or Retail Studies Academia, our academic CVs showcase your peer-reviewed publications, research grants, industry partnerships, and contribution to consumer and retail knowledge advancement.<br/><br/>Our FMCG and retail academic CVs emphasize your ability to conduct rigorous research while maintaining relevance to evolving consumer markets, positioning you as a leader in academic-commercial collaboration and consumer behavior research.`,
  },
  'legal-compliance': {
    industrySubtitle: 'For Legal & Compliance Professionals',
    description: `<strong style="color: #2563eb;">Build compelling academic cases with authoritative scholarly CVs! Let our Academic CV Writing service advocate for your path to legal research excellence! ⚖️📋</strong><br/><br/>Our legally-focused writers create authoritative academic CVs for legal researchers, law professors, and compliance academics—showcasing scholarly achievements and legal expertise. 🏛️🎓 Academic legal authority for scholarly advocacy.`,
    detailedDescription: `Academic careers in law, legal studies, and compliance research require CVs that demonstrate both scholarly excellence and practical legal understanding. Our specialized writers create comprehensive academic CVs highlighting your legal research, law review publications, legal clinic experience, or policy analysis contributions.<br/><br/>Whether pursuing positions in Law Faculty, Legal Research, or Policy Studies Academia, our academic CVs showcase your peer-reviewed publications, research grants, bar admissions, legal practice experience, and contribution to legal knowledge advancement.<br/><br/>Our legal academic CVs emphasize your ability to conduct rigorous legal research while addressing real-world legal challenges, positioning you as a bridge between academic legal theory and practical legal application.`,
  },
  'public-sector-government': {
    industrySubtitle: 'For Public Sector & Government Professionals',
    description: `<strong style="color: #2563eb;">Serve academic distinction with impactful scholarly CVs! Let our Academic CV Writing service govern your path to public administration research excellence! 🏛️🌟</strong><br/><br/>Our public service-focused writers create impactful academic CVs for policy researchers, public administration academics, and government scholars—showcasing research achievements and civic expertise. 📋🎓 Academic civic duty for scholarly public service.`,
    detailedDescription: `Academic careers in public administration, policy studies, and government research require CVs that demonstrate both scholarly rigor and public service understanding. Our specialized writers create comprehensive academic CVs highlighting your research in public policy, governance studies, political science, or public management.<br/><br/>Whether pursuing positions in Public Administration Faculty, Policy Research, or Government Studies Academia, our academic CVs showcase your peer-reviewed publications, research grants, government experience, policy analysis, and contribution to public administration knowledge.<br/><br/>Our public sector academic CVs emphasize your ability to conduct rigorous research while addressing real-world governance challenges, positioning you as a bridge between academic theory and practical public service application.`,
  },
  'chemicals-materials': {
    industrySubtitle: 'For Chemicals & Materials Professionals',
    description: `<strong style="color: #2563eb;">Formulate academic success with scientifically precise scholarly CVs! Let our Academic CV Writing service engineer compelling applications for chemistry and materials research excellence! ⚗️🧪</strong><br/><br/>Our science-focused writers create precise academic CVs for chemistry researchers, materials scientists, and chemical academics—showcasing research achievements and scientific innovation. 🔬🎓 Academic scientific excellence for scholarly formulation.`,
    detailedDescription: `Academic careers in chemistry, materials science, and chemical engineering require CVs that demonstrate both research excellence and practical scientific application. Our specialized writers create comprehensive academic CVs highlighting your research in chemical synthesis, materials development, process chemistry, or environmental chemistry.<br/><br/>Whether pursuing positions in Chemistry Faculty, Materials Research, or Chemical Engineering Academia, our academic CVs showcase your peer-reviewed publications, research grants, patent applications, laboratory management, and contribution to chemical sciences knowledge advancement.<br/><br/>Our chemistry and materials academic CVs emphasize your ability to conduct rigorous research while addressing real-world scientific challenges, positioning you as a leader in translating academic research into practical scientific innovation and technological advancement.`,
  },
}

const AcademicCVWritingPageContent = () => {
  const searchParams = useSearchParams()
  const industry = searchParams.get('industry')

  const industryContent =
    industry && industrySpecificContent[industry as keyof typeof industrySpecificContent]

  const serviceData = {
    ...servicesData.academicCvWriting,
    service: {
      ...servicesData.academicCvWriting.service,
      ...(industryContent && {
        description: industryContent.description,
        detailedDescription: industryContent.detailedDescription,
      }),
    },
    ...(industryContent && {
      industrySubtitle: industryContent.industrySubtitle,
    }),
  }

  return <ServiceProductPage {...serviceData} />
}

export default AcademicCVWritingPageContent
