'use client'

import { useSearchParams } from 'next/navigation'
import ServiceProductPage from '../ServiceProductPage'
import { servicesData } from '@/data/servicesData'

// Industry-specific content for Cover Letter Writing
const industrySpecificContent = {
  'construction-industry': {
    industrySubtitle: 'For Construction Industry Professionals',
    description: `<strong style="color: #2563eb;">Build compelling career foundations with expert cover letters! Let our Cover Letter Writing service construct your path to construction excellence! 🏗️📝</strong><br/><br/>Our construction-focused writers craft powerful cover letters for architects, engineers, and project managers—showcasing technical expertise and safety leadership. 🚧✨ Professional blueprints for construction career success.`,
    detailedDescription: `In the competitive construction industry, your cover letter needs to demonstrate technical competency, safety consciousness, and project leadership capabilities. Our specialized writers understand construction terminology, project management methodologies, and safety regulations, creating cover letters that resonate with construction industry hiring managers and project directors.<br/><br/>Whether you're applying for positions as a Construction Project Manager, Site Supervisor, Civil Engineer, Architect, or any construction-related role, our cover letters highlight your relevant certifications (PMP, OSHA, LEED), project achievements, budget management experience, and commitment to safety excellence. We showcase your ability to manage complex construction projects, coordinate multidisciplinary teams, and deliver projects on time and within budget.<br/><br/>Our construction industry cover letters emphasize quantifiable achievements such as project completion rates, cost savings, safety record improvements, and successful management of large-scale construction projects, positioning you as a results-driven professional who understands the unique demands of the construction industry.`,
  },
  'energy-oil-gas': {
    industrySubtitle: 'For Energy, Oil & Gas Professionals',
    description: `<strong style="color: #2563eb;">Power your career advancement with dynamic cover letters! Let our Cover Letter Writing service fuel your path to energy sector leadership! ⚡🛢️</strong><br/><br/>Our energy-focused writers create impactful cover letters for petroleum engineers, renewable energy specialists, and operations managers—showcasing technical expertise and industry insight. 🏭📝 Professional energy for career advancement.`,
    detailedDescription: `The energy sector demands professionals who understand complex technical operations, safety protocols, and evolving industry trends. Our specialized writers create cover letters that demonstrate your expertise in upstream/downstream operations, renewable energy technologies, environmental compliance, and operational efficiency improvements.<br/><br/>Whether targeting roles in Oil & Gas Operations, Renewable Energy Development, Energy Trading, or Environmental Compliance, our cover letters highlight your technical certifications, operational achievements, safety record, and understanding of energy market dynamics. We showcase your ability to manage complex energy projects, optimize production processes, and contribute to sustainable energy transitions.<br/><br/>Our energy industry cover letters emphasize quantifiable results such as production optimization percentages, cost reduction achievements, safety incident reductions, and successful implementation of new energy technologies, positioning you as a forward-thinking professional ready to drive energy sector innovation.`,
  },
  'tech-it': {
    industrySubtitle: 'For Technology & IT Professionals',
    description: `<strong style="color: #2563eb;">Debug your career potential with precision-coded cover letters! Let our Cover Letter Writing service program your path to tech excellence! 💻🚀</strong><br/><br/>Our tech-savvy writers develop cutting-edge cover letters for software engineers, data scientists, and IT managers—showcasing technical innovation and problem-solving expertise. 🔧📝 Digital narratives engineered for tech success.`,
    detailedDescription: `In the fast-evolving technology landscape, your cover letter must demonstrate technical expertise, innovation capabilities, and adaptability to emerging technologies. Our specialized writers understand current tech stacks, development methodologies, and digital transformation trends, creating cover letters that speak the language of technology hiring managers and CTOs.<br/><br/>Whether you're targeting roles in Software Development, Data Science, Cybersecurity, Cloud Computing, or IT Management, our cover letters highlight your programming languages, framework expertise, project accomplishments, and contribution to technical innovation. We showcase your ability to solve complex technical challenges, lead development teams, and drive digital transformation initiatives.<br/><br/>Our technology cover letters emphasize specific achievements such as application performance improvements, user base growth, system optimization results, and successful implementation of new technologies, positioning you as a technical leader ready to drive innovation in competitive tech markets.`,
  },
  'healthcare-pharma': {
    industrySubtitle: 'For Healthcare & Pharmaceutical Professionals',
    description: `<strong style="color: #2563eb;">Prescribe career success with professionally crafted cover letters! Let our Cover Letter Writing service diagnose your path to healthcare excellence! 🏥💊</strong><br/><br/>Our healthcare-focused writers create professional cover letters for medical professionals, pharmaceutical specialists, and healthcare administrators—showcasing clinical expertise and patient care commitment. 🩺📝 Medical professionalism for healthcare advancement.`,
    detailedDescription: `Healthcare and pharmaceutical industries require professionals who demonstrate clinical competency, regulatory knowledge, and commitment to patient outcomes. Our specialized writers understand medical terminology, pharmaceutical processes, healthcare regulations, and quality standards, creating cover letters that resonate with healthcare hiring managers and medical directors.<br/><br/>Whether targeting roles in Clinical Research, Pharmaceutical Development, Healthcare Administration, Medical Device Sales, or Direct Patient Care, our cover letters highlight your clinical experience, regulatory compliance knowledge, research contributions, and patient outcome improvements. We showcase your ability to work in regulated environments, collaborate with multidisciplinary teams, and contribute to advancing healthcare quality.<br/><br/>Our healthcare cover letters emphasize quantifiable achievements such as patient satisfaction scores, clinical trial success rates, regulatory approval timelines, and quality improvement initiatives, positioning you as a healthcare professional committed to excellence in patient care and medical innovation.`,
  },
  'banking-financial-services-insurance': {
    industrySubtitle: 'For Banking, Financial Services & Insurance Professionals',
    description: `<strong style="color: #2563eb;">Invest in career excellence with sophisticated cover letters! Let our Cover Letter Writing service calculate your path to financial sector leadership! 💰📈</strong><br/><br/>Our finance-focused writers create sophisticated cover letters for investment bankers, financial analysts, and insurance professionals—showcasing analytical expertise and market insight. 🏦📝 Financial intelligence for career investment.`,
    detailedDescription: `The financial services industry demands professionals who understand market dynamics, regulatory requirements, and risk management principles. Our specialized writers create cover letters that demonstrate your analytical capabilities, financial modeling expertise, regulatory compliance knowledge, and client relationship management skills.<br/><br/>Whether targeting roles in Investment Banking, Financial Planning, Risk Management, Insurance Underwriting, or Wealth Management, our cover letters highlight your financial certifications (CFA, FRM, CPA), analytical achievements, client portfolio growth, and contribution to revenue generation. We showcase your ability to analyze complex financial data, manage client relationships, and navigate regulatory environments.<br/><br/>Our financial services cover letters emphasize quantifiable results such as portfolio performance improvements, revenue growth percentages, risk reduction achievements, and successful client acquisition rates, positioning you as a financial professional ready to drive results in competitive financial markets.`,
  },
  'sales-marketing': {
    industrySubtitle: 'For Sales & Marketing Professionals',
    description: `<strong style="color: #2563eb;">Sell your potential with persuasive cover letters! Let our Cover Letter Writing service market your talents for sales and marketing excellence! 📊🎯</strong><br/><br/>Our results-driven writers create compelling cover letters for sales executives, marketing managers, and business development professionals—showcasing revenue achievements and market insight. 📈📝 Sales excellence for career persuasion.`,
    detailedDescription: `Sales and marketing professionals need cover letters that demonstrate revenue generation capabilities, market understanding, and customer relationship expertise. Our specialized writers understand sales methodologies, marketing strategies, and customer acquisition techniques, creating cover letters that showcase your commercial achievements and market impact.<br/><br/>Whether targeting roles in B2B Sales, Digital Marketing, Brand Management, Business Development, or Account Management, our cover letters highlight your sales performance, marketing campaign successes, customer retention rates, and contribution to business growth. We showcase your ability to understand customer needs, develop effective marketing strategies, and drive revenue results.<br/><br/>Our sales and marketing cover letters emphasize specific achievements such as quota attainment percentages, lead generation improvements, customer acquisition costs, and successful product launch results, positioning you as a commercial professional ready to drive business growth and market expansion.`,
  },
  'engineering-manufacturing': {
    industrySubtitle: 'For Engineering & Manufacturing Professionals',
    description: `<strong style="color: #2563eb;">Engineer career success with precision-crafted cover letters! Let our Cover Letter Writing service manufacture your path to engineering excellence! ⚙️🏭</strong><br/><br/>Our technical writers create robust cover letters for mechanical engineers, manufacturing managers, and quality specialists—showcasing technical expertise and operational excellence. 🔧📝 Engineering precision for career advancement.`,
    detailedDescription: `Engineering and manufacturing industries require professionals who demonstrate technical competency, problem-solving abilities, and operational efficiency expertise. Our specialized writers understand engineering principles, manufacturing processes, quality standards, and continuous improvement methodologies, creating cover letters that resonate with engineering managers and manufacturing directors.<br/><br/>Whether targeting roles in Product Design, Process Engineering, Manufacturing Operations, Quality Assurance, or Project Management, our cover letters highlight your technical certifications (PE, Six Sigma, PMP), design achievements, process improvements, and contribution to operational excellence. We showcase your ability to solve complex technical challenges, lead cross-functional teams, and drive manufacturing efficiency.<br/><br/>Our engineering cover letters emphasize quantifiable results such as cost reduction percentages, efficiency improvements, quality enhancement metrics, and successful project delivery timelines, positioning you as an engineering professional ready to drive technical innovation and operational excellence.`,
  },
  'strategy-consulting': {
    industrySubtitle: 'For Strategy & Consulting Professionals',
    description: `<strong style="color: #2563eb;">Strategize career impact with analytically precise cover letters! Let our Cover Letter Writing service consult on your path to strategic excellence! 🎯📊</strong><br/><br/>Our strategy-focused writers create analytical cover letters for management consultants, strategy advisors, and business analysts—showcasing problem-solving expertise and strategic insight. 📈📝 Strategic thinking for career consulting.`,
    detailedDescription: `Strategy and consulting professionals need cover letters that demonstrate analytical thinking, problem-solving capabilities, and client impact. Our specialized writers understand consulting methodologies, strategic frameworks, and business analysis techniques, creating cover letters that showcase your ability to solve complex business challenges and drive organizational transformation.<br/><br/>Whether targeting roles in Management Consulting, Strategy Development, Business Analysis, or Organizational Change, our cover letters highlight your analytical achievements, client project successes, strategic recommendations, and contribution to business improvement. We showcase your ability to analyze complex business situations, develop actionable recommendations, and manage client relationships effectively.<br/><br/>Our consulting cover letters emphasize specific achievements such as cost savings generated, revenue improvements, process efficiency gains, and successful change management initiatives, positioning you as a strategic professional ready to drive business transformation and deliver measurable client value.`,
  },
  'logistics-supply-chain': {
    industrySubtitle: 'For Logistics & Supply Chain Professionals',
    description: `<strong style="color: #2563eb;">Deliver career success with operationally excellent cover letters! Let our Cover Letter Writing service optimize your path to logistics leadership! 🚚📦</strong><br/><br/>Our operations-focused writers create efficient cover letters for supply chain managers, logistics coordinators, and procurement specialists—showcasing operational expertise and strategic vision. ⚡📝 Operational excellence for career optimization.`,
    detailedDescription: `Logistics and supply chain industries require professionals who understand complex operational processes, vendor management, and cost optimization strategies. Our specialized writers create cover letters that demonstrate your expertise in supply chain management, logistics coordination, inventory optimization, and vendor relationship management.<br/><br/>Whether targeting roles in Supply Chain Management, Logistics Operations, Procurement, or Distribution Management, our cover letters highlight your operational achievements, cost reduction initiatives, vendor management successes, and contribution to supply chain efficiency. We showcase your ability to optimize complex logistics networks, manage global supply chains, and drive operational improvements.<br/><br/>Our logistics cover letters emphasize quantifiable results such as cost reduction percentages, delivery time improvements, inventory optimization achievements, and successful vendor negotiation outcomes, positioning you as an operations professional ready to drive supply chain excellence and logistical innovation.`,
  },
  'hospitality-tourism': {
    industrySubtitle: 'For Hospitality & Tourism Professionals',
    description: `<strong style="color: #2563eb;">Create exceptional career experiences with welcoming cover letters! Let our Cover Letter Writing service host your journey to hospitality excellence! 🏨✈️</strong><br/><br/>Our service-focused writers create warm cover letters for hotel managers, tourism specialists, and event coordinators—showcasing service excellence and cultural competency. 🌟📝 Hospitality warmth for career distinction.`,
    detailedDescription: `Hospitality and tourism industries require professionals who demonstrate service excellence, cultural sensitivity, and guest experience management capabilities. Our specialized writers understand hospitality operations, tourism trends, and customer service principles, creating cover letters that showcase your commitment to exceptional guest experiences and operational excellence.<br/><br/>Whether targeting roles in Hotel Management, Event Planning, Tourism Development, Restaurant Operations, or Guest Services, our cover letters highlight your service achievements, guest satisfaction improvements, cultural competency, and contribution to revenue growth. We showcase your ability to create memorable experiences, manage diverse teams, and excel in fast-paced service environments.<br/><br/>Our hospitality cover letters emphasize specific achievements such as guest satisfaction scores, revenue growth percentages, event success metrics, and operational efficiency improvements, positioning you as a hospitality professional committed to creating exceptional experiences and driving service excellence.`,
  },
  'media-entertainment': {
    industrySubtitle: 'For Media & Entertainment Professionals',
    description: `<strong style="color: #2563eb;">Direct your career spotlight with creatively compelling cover letters! Let our Cover Letter Writing service produce award-worthy applications for media success! 🎬🎭</strong><br/><br/>Our creative writers craft captivating cover letters for content creators, producers, and media professionals—showcasing artistic vision and commercial success. 🎨📝 Creative excellence for media storytelling.`,
    detailedDescription: `Media and entertainment industries require professionals who demonstrate creative capabilities, technical expertise, and understanding of audience engagement. Our specialized writers create cover letters that showcase your creative projects, technical skills, collaborative abilities, and contribution to successful media productions.<br/><br/>Whether targeting roles in Film Production, Content Creation, Media Marketing, Broadcasting, or Entertainment Management, our cover letters highlight your creative achievements, technical proficiencies, audience engagement successes, and contribution to successful media projects. We showcase your ability to create compelling content, manage creative teams, and understand evolving media landscapes.<br/><br/>Our media cover letters emphasize specific achievements such as audience growth percentages, project completion metrics, creative award recognition, and successful content performance data, positioning you as a media professional ready to create engaging content and drive creative innovation.`,
  },
  'human-resources': {
    industrySubtitle: 'For Human Resources Professionals',
    description: `<strong style="color: #2563eb;">Develop exceptional career narratives with strategic cover letters! Let our Cover Letter Writing service recruit success for your HR journey! 👥💼</strong><br/><br/>Our people-focused writers create strategic cover letters for HR managers, talent acquisition specialists, and organizational development professionals—showcasing people expertise and strategic vision. 🎯📝 People strategy for HR advancement.`,
    detailedDescription: `Human resources professionals need cover letters that demonstrate people management expertise, organizational development capabilities, and strategic HR thinking. Our specialized writers understand HR best practices, employment law, and organizational psychology, creating cover letters that showcase your ability to drive employee engagement, talent development, and organizational effectiveness.<br/><br/>Whether targeting roles in Talent Acquisition, Employee Relations, HR Business Partnership, Training & Development, or Compensation & Benefits, our cover letters highlight your HR achievements, employee engagement improvements, talent retention successes, and contribution to organizational development. We showcase your ability to align HR strategies with business objectives and drive positive organizational change.<br/><br/>Our HR cover letters emphasize quantifiable results such as employee retention improvements, recruitment efficiency gains, training program success rates, and employee satisfaction score enhancements, positioning you as an HR professional ready to drive organizational success through effective people management.`,
  },
  'fmcg-retail': {
    industrySubtitle: 'For FMCG & Retail Professionals',
    description: `<strong style="color: #2563eb;">Stock your career future with market-ready cover letters! Let our Cover Letter Writing service retail your potential for FMCG success! 🛒🏪</strong><br/><br/>Our consumer-focused writers create compelling cover letters for brand managers, retail buyers, and category specialists—showcasing commercial expertise and consumer insight. 📊📝 Consumer intelligence for retail advancement.`,
    detailedDescription: `FMCG and retail industries require professionals who understand consumer behavior, market trends, and commercial strategies. Our specialized writers create cover letters that demonstrate your brand management expertise, retail operations knowledge, consumer insights, and contribution to revenue growth and market expansion.<br/><br/>Whether targeting roles in Brand Management, Category Management, Retail Operations, Merchandising, or Consumer Marketing, our cover letters highlight your commercial achievements, market share improvements, product launch successes, and contribution to brand growth. We showcase your ability to understand consumer needs, develop effective retail strategies, and drive commercial results.<br/><br/>Our FMCG and retail cover letters emphasize specific achievements such as sales growth percentages, market share gains, inventory optimization results, and successful product launch metrics, positioning you as a commercial professional ready to drive consumer market success and retail innovation.`,
  },
  'legal-compliance': {
    industrySubtitle: 'For Legal & Compliance Professionals',
    description: `<strong style="color: #2563eb;">Build compelling cases for career advancement! Let our Cover Letter Writing service advocate for your path to legal excellence! ⚖️📋</strong><br/><br/>Our legally-focused writers create authoritative cover letters for attorneys, compliance officers, and legal analysts—showcasing legal expertise and analytical rigor. 🏛️📝 Legal authority for career advocacy.`,
    detailedDescription: `Legal and compliance professionals need cover letters that demonstrate legal expertise, analytical thinking, and regulatory knowledge. Our specialized writers understand legal terminology, compliance frameworks, and regulatory requirements, creating cover letters that showcase your legal achievements, case management experience, and contribution to organizational risk management.<br/><br/>Whether targeting roles in Corporate Law, Compliance Management, Legal Consulting, Regulatory Affairs, or Risk Management, our cover letters highlight your legal certifications, case successes, compliance program development, and contribution to organizational legal strategy. We showcase your ability to navigate complex legal challenges, manage regulatory requirements, and provide strategic legal counsel.<br/><br/>Our legal cover letters emphasize specific achievements such as successful case outcomes, compliance program effectiveness, risk reduction metrics, and regulatory approval successes, positioning you as a legal professional ready to provide expert counsel and drive organizational compliance excellence.`,
  },
  'public-sector-government': {
    industrySubtitle: 'For Public Sector & Government Professionals',
    description: `<strong style="color: #2563eb;">Serve with distinction through compelling cover letters! Let our Cover Letter Writing service govern your path to public sector excellence! 🏛️🌟</strong><br/><br/>Our public service-focused writers create impactful cover letters for government officials, policy analysts, and public administrators—showcasing civic commitment and analytical expertise. 📋📝 Civic duty for public service advancement.`,
    detailedDescription: `Public sector and government professionals need cover letters that demonstrate public service commitment, policy expertise, and analytical capabilities. Our specialized writers understand government operations, policy development processes, and public administration principles, creating cover letters that showcase your contribution to public service and community impact.<br/><br/>Whether targeting roles in Policy Development, Public Administration, Government Relations, Program Management, or Regulatory Affairs, our cover letters highlight your public service achievements, policy analysis contributions, program management successes, and commitment to civic engagement. We showcase your ability to serve public interests, develop effective policies, and manage government programs efficiently.<br/><br/>Our public sector cover letters emphasize specific achievements such as policy implementation success rates, program efficiency improvements, stakeholder engagement results, and community impact metrics, positioning you as a public service professional committed to effective governance and positive community outcomes.`,
  },
  'chemicals-materials': {
    industrySubtitle: 'For Chemicals & Materials Professionals',
    description: `<strong style="color: #2563eb;">Formulate career success with scientifically precise cover letters! Let our Cover Letter Writing service engineer compelling applications for chemicals and materials excellence! ⚗️🧪</strong><br/><br/>Our science-focused writers create precise cover letters for research scientists, process engineers, and materials specialists—showcasing technical expertise and innovation potential. 🔬📝 Scientific excellence for career formulation.`,
    detailedDescription: `Chemicals and materials industries require professionals who demonstrate technical expertise, research capabilities, and innovation potential. Our specialized writers understand chemical processes, materials science principles, and research methodologies, creating cover letters that showcase your technical achievements, research contributions, and ability to drive scientific innovation.<br/><br/>Whether targeting roles in R&D, Process Engineering, Quality Control, Product Development, or Technical Sales, our cover letters highlight your technical certifications, research publications, process improvements, and contribution to product innovation. We showcase your ability to solve complex technical challenges, manage laboratory operations, and translate research into commercial applications.<br/><br/>Our chemicals and materials cover letters emphasize quantifiable results such as process efficiency improvements, product development timelines, quality enhancement metrics, and successful research project outcomes, positioning you as a technical professional ready to drive scientific innovation and technological advancement.`,
  },
}

const CoverLetterWritingPageContent = () => {
  const searchParams = useSearchParams()
  const industry = searchParams.get('industry')

  const industryContent =
    industry && industrySpecificContent[industry as keyof typeof industrySpecificContent]

  const serviceData = {
    ...servicesData.coverLetter, // <-- update to the correct property name
    service: {
      ...servicesData.coverLetter.service, // <-- update to the correct property name
      ...(industryContent && {
        description: industryContent.description,
        detailedDescription: industryContent.detailedDescription,
      }),
    },
    ...(industryContent && {
      industrySubtitle: industryContent.industrySubtitle,
    }),
  }

  return <ServiceProductPage {...serviceData} />
}

export default CoverLetterWritingPageContent
