'use client'

import { useSearchParams } from 'next/navigation'
import ServiceProductPage from '../ServiceProductPage'
import { servicesData } from '@/data/servicesData'

// Industry-specific content for Interview Coaching
const industrySpecificContent = {
  'construction-industry': {
    industrySubtitle: 'For Finance & Banking Professionals',
    description: `<strong style="color: #2563eb;">Build confidence for construction interviews! Let our Interview Coaching service construct your path to interview excellence and career success! 🏗️🎯</strong><br/><br/>Our construction-focused coaches prepare professionals for technical interviews with architects, engineers, and project management roles—mastering industry-specific questions and scenarios. 🚧✨ Professional preparation for construction career advancement.`,
    detailedDescription: `Construction industry interviews require demonstration of technical knowledge, safety consciousness, project management skills, and leadership capabilities. Our specialized interview coaches understand construction terminology, project methodologies, safety regulations, and industry-specific challenges, preparing you for comprehensive construction industry interviews.<br/><br/>Whether you're interviewing for Construction Project Manager, Site Supervisor, Civil Engineer, Architect, or Safety Manager positions, our coaching covers technical questioning about construction methods, safety protocols, project scheduling, budget management, and team coordination. We prepare you for scenario-based questions about handling construction delays, managing subcontractors, ensuring safety compliance, and delivering projects on time and within budget.<br/><br/>Our construction interview coaching includes practice with industry-specific behavioral questions, technical problem-solving scenarios, safety incident discussions, and project management case studies. We help you articulate your construction experience, certifications (PMP, OSHA, LEED), project achievements, and demonstrate your ability to lead construction teams while maintaining the highest safety and quality standards expected in the construction industry.`,
  },
  'energy-oil-gas': {
    industrySubtitle: 'For Energy, Oil & Gas Professionals',
    description: `<strong style="color: #2563eb;">Power your interview performance with dynamic preparation! Let our Interview Coaching service fuel your success in energy sector interviews! ⚡🛢️</strong><br/><br/>Our energy-focused coaches prepare professionals for technical interviews in petroleum engineering, renewable energy, and operations management—mastering sector-specific challenges and opportunities. 🏭🎯 Professional energy for interview advancement.`,
    detailedDescription: `Energy sector interviews demand demonstration of technical expertise, safety consciousness, environmental awareness, and operational efficiency understanding. Our specialized coaches prepare you for complex technical questions about upstream/downstream operations, renewable energy technologies, safety protocols, and environmental compliance.<br/><br/>Whether interviewing for Petroleum Engineer, Renewable Energy Specialist, Operations Manager, or Environmental Compliance roles, our coaching covers technical discussions about production optimization, safety management, environmental impact, and energy market dynamics. We prepare you for scenario-based questions about operational challenges and energy transition strategies.<br/><br/>Our energy interview coaching emphasizes quantifiable achievements in production efficiency, safety improvements, environmental compliance, and operational cost reduction, helping you demonstrate your contribution to sustainable energy operations and innovation.`,
  },
  'tech-it': {
    industrySubtitle: 'For Technology & IT Professionals',
    description: `<strong style="color: #2563eb;">Debug your interview potential with precision-coded preparation! Let our Interview Coaching service program your path to tech interview excellence! 💻🚀</strong><br/><br/>Our tech-savvy coaches develop cutting-edge interview strategies for software engineers, data scientists, and IT managers—mastering technical challenges and behavioral scenarios. 🔧🎯 Digital preparation engineered for tech success.`,
    detailedDescription: `Technology interviews require demonstration of coding skills, system design knowledge, problem-solving abilities, and adaptability to emerging technologies. Our specialized coaches prepare you for technical coding challenges, system architecture discussions, algorithmic problem-solving, and behavioral questions specific to technology environments.<br/><br/>Whether interviewing for Software Developer, Data Scientist, DevOps Engineer, or IT Manager positions, our coaching covers technical assessments, whiteboard coding, system design scenarios, and discussions about technology stacks, development methodologies, and project delivery approaches. We prepare you for both technical depth and collaborative problem-solving demonstrations.<br/><br/>Our tech interview coaching includes practice with live coding sessions, technical presentation skills, and articulating complex technical concepts to both technical and non-technical audiences, positioning you as a well-rounded technology professional ready for leadership and innovation roles.`,
  },
  'healthcare-pharma': {
    industrySubtitle: 'For Healthcare & Pharmaceutical Professionals',
    description: `<strong style="color: #2563eb;">Prescribe interview success with professional preparation! Let our Interview Coaching service diagnose your path to healthcare interview excellence! 🏥💊</strong><br/><br/>Our healthcare-focused coaches prepare professionals for clinical interviews with medical institutions, pharmaceutical companies, and healthcare organizations—mastering patient care and regulatory scenarios. 🩺🎯 Medical preparation for healthcare advancement.`,
    detailedDescription: `Healthcare and pharmaceutical interviews require demonstration of clinical competency, regulatory knowledge, patient safety commitment, and ethical decision-making capabilities. Our specialized coaches prepare you for clinical scenario discussions, regulatory compliance questions, patient care situations, and healthcare quality improvement challenges.<br/><br/>Whether interviewing for Clinical Research, Pharmaceutical Development, Healthcare Administration, or Direct Patient Care roles, our coaching covers medical knowledge assessments, ethical dilemma discussions, regulatory compliance scenarios, and patient outcome improvement strategies. We prepare you for both technical medical knowledge and compassionate patient care demonstrations.<br/><br/>Our healthcare interview coaching emphasizes patient safety, quality improvement achievements, regulatory compliance experience, and your commitment to advancing healthcare outcomes through evidence-based practice and continuous professional development.`,
  },
  'banking-financial-services-insurance': {
    industrySubtitle: 'For Banking, Financial Services & Insurance Professionals',
    description: `<strong style="color: #2563eb;">Invest in interview excellence with sophisticated preparation! Let our Interview Coaching service calculate your path to financial sector interview success! 💰📈</strong><br/><br/>Our finance-focused coaches create sophisticated interview strategies for investment bankers, financial analysts, and insurance professionals—mastering analytical challenges and market scenarios. 🏦🎯 Financial intelligence for interview investment.`,
    detailedDescription: `Financial services interviews require demonstration of analytical capabilities, market knowledge, regulatory understanding, and client relationship management skills. Our specialized coaches prepare you for quantitative assessments, market analysis discussions, risk management scenarios, and client service challenges specific to financial environments.<br/><br/>Whether interviewing for Investment Banking, Financial Planning, Risk Management, or Insurance roles, our coaching covers financial modeling assessments, market trend analysis, regulatory compliance discussions, and client relationship scenarios. We prepare you for both technical financial knowledge and professional client interaction demonstrations.<br/><br/>Our financial interview coaching emphasizes quantifiable achievements in portfolio performance, risk reduction, client satisfaction, and revenue generation, helping you demonstrate your ability to deliver measurable results in competitive financial markets.`,
  },
  'sales-marketing': {
    industrySubtitle: 'For Sales & Marketing Professionals',
    description: `<strong style="color: #2563eb;">Sell your potential with persuasive interview preparation! Let our Interview Coaching service market your success in sales and marketing interviews! 📊🎯</strong><br/><br/>Our results-driven coaches create compelling interview strategies for sales executives, marketing managers, and business development professionals—mastering commercial challenges and customer scenarios. 📈🎯 Sales excellence for interview persuasion.`,
    detailedDescription: `Sales and marketing interviews require demonstration of revenue generation capabilities, customer understanding, market insight, and persuasive communication skills. Our specialized coaches prepare you for sales simulation exercises, marketing strategy discussions, customer relationship scenarios, and business development challenges.<br/><br/>Whether interviewing for B2B Sales, Digital Marketing, Brand Management, or Business Development roles, our coaching covers sales technique demonstrations, marketing campaign presentations, customer needs analysis, and revenue growth strategy discussions. We prepare you for both quantitative performance metrics and qualitative relationship-building demonstrations.<br/><br/>Our sales and marketing interview coaching emphasizes specific achievements in quota attainment, lead generation, customer acquisition, and market expansion, helping you demonstrate your ability to drive business growth and market success.`,
  },
  'engineering-manufacturing': {
    industrySubtitle: 'For Engineering & Manufacturing Professionals',
    description: `<strong style="color: #2563eb;">Engineer interview success with precision-crafted preparation! Let our Interview Coaching service manufacture your path to engineering interview excellence! ⚙️🏭</strong><br/><br/>Our technical coaches create robust interview strategies for mechanical engineers, manufacturing managers, and quality specialists—mastering technical challenges and operational scenarios. 🔧🎯 Engineering precision for interview advancement.`,
    detailedDescription: `Engineering and manufacturing interviews require demonstration of technical expertise, problem-solving abilities, design thinking, and operational efficiency understanding. Our specialized coaches prepare you for technical assessments, design challenges, process improvement discussions, and quality management scenarios specific to engineering environments.<br/><br/>Whether interviewing for Product Design, Process Engineering, Manufacturing Operations, or Quality Assurance roles, our coaching covers technical problem-solving exercises, design methodology discussions, process optimization scenarios, and quality improvement presentations. We prepare you for both technical depth and practical application demonstrations.<br/><br/>Our engineering interview coaching emphasizes quantifiable achievements in cost reduction, efficiency improvements, quality enhancements, and successful project delivery, helping you demonstrate your ability to drive technical innovation and operational excellence.`,
  },
  'strategy-consulting': {
    industrySubtitle: 'For Strategy & Consulting Professionals',
    description: `<strong style="color: #2563eb;">Strategize interview impact with analytically precise preparation! Let our Interview Coaching service consult on your path to strategic interview excellence! 🎯📊</strong><br/><br/>Our strategy-focused coaches create analytical interview strategies for management consultants, strategy advisors, and business analysts—mastering case studies and client scenarios. 📈🎯 Strategic thinking for interview consulting.`,
    detailedDescription: `Strategy and consulting interviews require demonstration of analytical thinking, problem-solving methodologies, client communication skills, and business acumen. Our specialized coaches prepare you for case study analysis, strategic framework applications, client presentation scenarios, and business problem-solving challenges.<br/><br/>Whether interviewing for Management Consulting, Strategy Development, Business Analysis, or Change Management roles, our coaching covers case interview techniques, strategic analysis frameworks, client interaction simulations, and business recommendation presentations. We prepare you for both analytical rigor and persuasive communication demonstrations.<br/><br/>Our consulting interview coaching emphasizes specific achievements in cost savings, revenue improvements, process optimization, and successful client engagements, helping you demonstrate your ability to deliver measurable value to clients and organizations.`,
  },
  'logistics-supply-chain': {
    industrySubtitle: 'For Logistics & Supply Chain Professionals',
    description: `<strong style="color: #2563eb;">Deliver interview success with operationally excellent preparation! Let our Interview Coaching service optimize your path to logistics interview excellence! 🚚📦</strong><br/><br/>Our operations-focused coaches create efficient interview strategies for supply chain managers, logistics coordinators, and procurement specialists—mastering operational challenges and efficiency scenarios. ⚡🎯 Operational excellence for interview optimization.`,
    detailedDescription: `Logistics and supply chain interviews require demonstration of operational expertise, process optimization abilities, vendor management skills, and cost reduction capabilities. Our specialized coaches prepare you for operational scenario discussions, supply chain optimization challenges, vendor relationship assessments, and logistics coordination simulations.<br/><br/>Whether interviewing for Supply Chain Management, Logistics Operations, Procurement, or Distribution roles, our coaching covers operational efficiency assessments, vendor negotiation scenarios, inventory optimization discussions, and cost reduction strategy presentations. We prepare you for both analytical problem-solving and practical implementation demonstrations.<br/><br/>Our logistics interview coaching emphasizes quantifiable achievements in cost reduction, delivery improvements, inventory optimization, and supplier relationship enhancement, helping you demonstrate your ability to drive operational excellence and supply chain innovation.`,
  },
  'hospitality-tourism': {
    industrySubtitle: 'For Hospitality & Tourism Professionals',
    description: `<strong style="color: #2563eb;">Create exceptional interview experiences with welcoming preparation! Let our Interview Coaching service host your journey to hospitality interview excellence! 🏨✈️</strong><br/><br/>Our service-focused coaches create warm interview strategies for hotel managers, tourism specialists, and event coordinators—mastering guest service and cultural scenarios. 🌟🎯 Hospitality warmth for interview distinction.`,
    detailedDescription: `Hospitality and tourism interviews require demonstration of service excellence, cultural sensitivity, guest experience management, and operational efficiency capabilities. Our specialized coaches prepare you for guest service scenarios, cultural competency assessments, crisis management situations, and revenue optimization discussions specific to hospitality environments.<br/><br/>Whether interviewing for Hotel Management, Event Planning, Tourism Development, or Guest Services roles, our coaching covers guest satisfaction scenarios, event coordination challenges, cultural awareness assessments, and service recovery simulations. We prepare you for both service excellence and business acumen demonstrations.<br/><br/>Our hospitality interview coaching emphasizes achievements in guest satisfaction scores, revenue growth, event success metrics, and operational improvements, helping you demonstrate your ability to create exceptional experiences while driving business results.`,
  },
  'media-entertainment': {
    industrySubtitle: 'For Media & Entertainment Professionals',
    description: `<strong style="color: #2563eb;">Direct your interview spotlight with creatively compelling preparation! Let our Interview Coaching service produce award-worthy interview performances! 🎬🎭</strong><br/><br/>Our creative coaches craft captivating interview strategies for content creators, producers, and media professionals—mastering creative challenges and collaboration scenarios. 🎨🎯 Creative excellence for media interview storytelling.`,
    detailedDescription: `Media and entertainment interviews require demonstration of creative capabilities, technical expertise, collaborative skills, and audience engagement understanding. Our specialized coaches prepare you for creative portfolio presentations, collaborative project discussions, audience analysis scenarios, and content strategy assessments.<br/><br/>Whether interviewing for Film Production, Content Creation, Media Marketing, or Entertainment Management roles, our coaching covers creative process discussions, technical skill demonstrations, team collaboration scenarios, and audience engagement strategy presentations. We prepare you for both creative vision and commercial viability demonstrations.<br/><br/>Our media interview coaching emphasizes achievements in audience growth, content performance, creative recognition, and successful project delivery, helping you demonstrate your ability to create compelling content while understanding commercial entertainment markets.`,
  },
  'human-resources': {
    industrySubtitle: 'For Human Resources Professionals',
    description: `<strong style="color: #2563eb;">Develop exceptional interview narratives with strategic preparation! Let our Interview Coaching service recruit success for your HR interview journey! 👥💼</strong><br/><br/>Our people-focused coaches create strategic interview approaches for HR managers, talent acquisition specialists, and organizational development professionals—mastering people challenges and strategic scenarios. 🎯🎯 People strategy for HR interview advancement.`,
    detailedDescription: `Human resources interviews require demonstration of people management expertise, organizational development capabilities, employment law knowledge, and strategic HR thinking. Our specialized coaches prepare you for employee relations scenarios, talent acquisition challenges, organizational change discussions, and HR metrics assessments.<br/><br/>Whether interviewing for Talent Acquisition, Employee Relations, Training & Development, or HR Leadership roles, our coaching covers conflict resolution scenarios, recruitment strategy discussions, performance management assessments, and organizational development presentations. We prepare you for both people-focused sensitivity and business-aligned strategic thinking.<br/><br/>Our HR interview coaching emphasizes achievements in employee retention, recruitment efficiency, training effectiveness, and organizational development success, helping you demonstrate your ability to drive organizational success through effective people management.`,
  },
  'fmcg-retail': {
    industrySubtitle: 'For FMCG & Retail Professionals',
    description: `<strong style="color: #2563eb;">Stock your interview success with market-ready preparation! Let our Interview Coaching service retail your potential for FMCG interview excellence! 🛒🏪</strong><br/><br/>Our consumer-focused coaches create compelling interview strategies for brand managers, retail buyers, and category specialists—mastering commercial challenges and consumer scenarios. 📊🎯 Consumer intelligence for retail interview advancement.`,
    detailedDescription: `FMCG and retail interviews require demonstration of commercial expertise, consumer understanding, brand management capabilities, and market analysis skills. Our specialized coaches prepare you for brand strategy discussions, consumer behavior assessments, retail operations scenarios, and market expansion challenges.<br/><br/>Whether interviewing for Brand Management, Category Management, Retail Operations, or Consumer Marketing roles, our coaching covers market analysis presentations, brand positioning discussions, consumer insight assessments, and commercial strategy scenarios. We prepare you for both creative brand thinking and analytical commercial performance.<br/><br/>Our FMCG and retail interview coaching emphasizes achievements in sales growth, market share gains, brand development success, and consumer engagement improvements, helping you demonstrate your ability to drive commercial success in competitive consumer markets.`,
  },
  'legal-compliance': {
    industrySubtitle: 'For Legal & Compliance Professionals',
    description: `<strong style="color: #2563eb;">Build compelling interview cases with authoritative preparation! Let our Interview Coaching service advocate for your legal interview excellence! ⚖️📋</strong><br/><br/>Our legally-focused coaches create authoritative interview strategies for attorneys, compliance officers, and legal analysts—mastering legal challenges and regulatory scenarios. 🏛️🎯 Legal authority for interview advocacy.`,
    detailedDescription: `Legal and compliance interviews require demonstration of legal expertise, analytical thinking, ethical reasoning, and regulatory knowledge. Our specialized coaches prepare you for legal case discussions, compliance scenario assessments, ethical dilemma analyses, and regulatory interpretation challenges.<br/><br/>Whether interviewing for Corporate Law, Compliance Management, Legal Analysis, or Risk Management roles, our coaching covers legal reasoning exercises, compliance program discussions, regulatory assessment scenarios, and ethical decision-making presentations. We prepare you for both legal technical knowledge and practical application demonstrations.<br/><br/>Our legal interview coaching emphasizes achievements in case success rates, compliance program effectiveness, risk mitigation, and regulatory approval success, helping you demonstrate your ability to provide expert legal counsel and ensure organizational compliance excellence.`,
  },
  'public-sector-government': {
    industrySubtitle: 'For Public Sector & Government Professionals',
    description: `<strong style="color: #2563eb;">Serve with interview distinction through impactful preparation! Let our Interview Coaching service govern your path to public sector interview excellence! 🏛️🌟</strong><br/><br/>Our public service-focused coaches create impactful interview strategies for government officials, policy analysts, and public administrators—mastering civic challenges and community scenarios. 📋🎯 Civic duty for public service interview advancement.`,
    detailedDescription: `Public sector and government interviews require demonstration of public service commitment, policy expertise, analytical capabilities, and stakeholder engagement skills. Our specialized coaches prepare you for policy analysis discussions, public administration scenarios, community engagement assessments, and government program evaluation challenges.<br/><br/>Whether interviewing for Policy Development, Public Administration, Program Management, or Community Engagement roles, our coaching covers policy impact assessments, stakeholder management scenarios, public communication presentations, and program effectiveness discussions. We prepare you for both analytical rigor and public service dedication demonstrations.<br/><br/>Our public sector interview coaching emphasizes achievements in policy implementation success, program efficiency improvements, stakeholder satisfaction, and community impact metrics, helping you demonstrate your commitment to effective governance and positive public outcomes.`,
  },
  'chemicals-materials': {
    industrySubtitle: 'For Chemicals & Materials Professionals',
    description: `<strong style="color: #2563eb;">Formulate interview success with scientifically precise preparation! Let our Interview Coaching service engineer compelling interview strategies for chemicals and materials excellence! ⚗️🧪</strong><br/><br/>Our science-focused coaches create precise interview approaches for research scientists, process engineers, and materials specialists—mastering technical challenges and innovation scenarios. 🔬🎯 Scientific excellence for interview formulation.`,
    detailedDescription: `Chemicals and materials interviews require demonstration of technical expertise, research capabilities, safety consciousness, and innovation potential. Our specialized coaches prepare you for technical problem-solving assessments, research methodology discussions, safety protocol scenarios, and product development challenges.<br/><br/>Whether interviewing for R&D, Process Engineering, Quality Control, or Product Development roles, our coaching covers technical analysis exercises, research presentation skills, safety management discussions, and innovation strategy assessments. We prepare you for both scientific rigor and practical application demonstrations.<br/><br/>Our chemicals and materials interview coaching emphasizes achievements in process improvements, product development success, quality enhancements, and research contributions, helping you demonstrate your ability to drive scientific innovation and technological advancement in chemical and materials industries.`,
  },
}

const InterviewCoachingPageContent = () => {
  const searchParams = useSearchParams()
  const industry = searchParams.get('industry')

  const industryContent =
    industry && industrySpecificContent[industry as keyof typeof industrySpecificContent]

  const serviceData = {
    ...servicesData.interviewCoaching,
    service: {
      ...servicesData.interviewCoaching.service,
      ...(industryContent && {
        description: industryContent.description,
        detailedDescription: industryContent.detailedDescription,
      }),
    },
    ...(industryContent && {
      industrySubtitle: industryContent.industrySubtitle,
    }),
  }

  return <ServiceProductPage {...serviceData} />
}

export default InterviewCoachingPageContent
