'use client'

import { useSearchParams } from 'next/navigation'
import ServiceProductPage from '../ServiceProductPage'
import { servicesData } from '@/data/servicesData'

// Industry-specific content for Membership Application Service
const industrySpecificContent = {
  'construction-industry': {
    industrySubtitle: 'For Government & Non-Profit Professionals',
    description: `<strong style="color: #2563eb;">Build your professional foundation with expert membership applications! Let our Membership Application service construct your path to construction industry recognition! 🏗️🏅</strong><br/><br/>Our construction-focused writers craft compelling applications for ICE, ASCE, CIOB, and professional engineering memberships—showcasing technical expertise and industry contributions. 🚧✨ Professional credentials for construction excellence.`,
    detailedDescription: `Professional membership in construction organizations like the Institution of Civil Engineers (ICE), American Society of Civil Engineers (ASCE), Chartered Institute of Building (CIOB), or professional engineering licensure requires detailed applications demonstrating technical competency, project experience, and professional development. Our specialized writers understand the specific requirements and evaluation criteria for construction industry professional memberships.<br/><br/>Whether you're applying for Chartered Engineer status, Professional Engineer licensure, or membership in construction management organizations, our service creates comprehensive applications that highlight your technical projects, professional responsibilities, continuing education, and contribution to construction industry advancement. We present your construction experience in formats that meet professional body requirements.<br/><br/>Our construction membership applications emphasize project complexity, technical leadership, safety achievements, and professional development activities, positioning you as a qualified construction professional committed to industry best practices and continuing professional growth. We ensure your application demonstrates the technical competency and professional standards required for construction industry recognition.`,
  },
  'energy-oil-gas': {
    industrySubtitle: 'For Energy, Oil & Gas Professionals',
    description: `<strong style="color: #2563eb;">Power your professional recognition with dynamic membership applications! Let our Membership Application service fuel your path to energy sector professional status! ⚡🛢️</strong><br/><br/>Our energy-focused writers create impactful applications for SPE, API, IEEE, and energy professional memberships—showcasing technical expertise and industry contributions. 🏭🏅 Professional energy for sector recognition.`,
    detailedDescription: `Professional membership in energy organizations like Society of Petroleum Engineers (SPE), American Petroleum Institute (API), Institute of Electrical and Electronics Engineers (IEEE Energy), or professional engineering bodies requires comprehensive applications demonstrating technical expertise, operational experience, and industry contribution. Our specialized writers understand energy sector professional requirements and membership criteria.<br/><br/>Whether applying for Professional Engineer status, Chartered Engineer recognition, or specialized energy industry memberships, our service creates detailed applications highlighting your technical projects, operational achievements, safety contributions, and professional development in energy sector roles.<br/><br/>Our energy membership applications emphasize technical innovation, operational excellence, environmental stewardship, and continuing education, positioning you as a qualified energy professional committed to advancing industry standards and sustainable energy practices.`,
  },
  'tech-it': {
    industrySubtitle: 'For Technology & IT Professionals',
    description: `<strong style="color: #2563eb;">Debug your professional credentials with precision-coded applications! Let our Membership Application service program your path to tech industry recognition! 💻🚀</strong><br/><br/>Our tech-savvy writers develop cutting-edge applications for IEEE, ACM, BCS, and technology professional memberships—showcasing innovation and technical excellence. 🔧🏅 Digital credentials engineered for tech success.`,
    detailedDescription: `Professional membership in technology organizations like Institute of Electrical and Electronics Engineers (IEEE), Association for Computing Machinery (ACM), British Computer Society (BCS), or specialized IT certifications requires applications demonstrating technical expertise, innovative contributions, and professional development. Our specialized writers understand technology sector professional standards and membership requirements.<br/><br/>Whether applying for Chartered IT Professional status, IEEE membership grades, or specialized technology certifications, our service creates comprehensive applications highlighting your software development projects, system implementations, research contributions, and technology innovation achievements.<br/><br/>Our technology membership applications emphasize technical innovation, collaborative development, continuous learning, and contribution to technology advancement, positioning you as a qualified technology professional committed to driving digital transformation and technical excellence.`,
  },
  'healthcare-pharma': {
    industrySubtitle: 'For Healthcare & Pharmaceutical Professionals',
    description: `<strong style="color: #2563eb;">Prescribe professional excellence with expertly crafted membership applications! Let our Membership Application service diagnose your path to healthcare industry recognition! 🏥💊</strong><br/><br/>Our healthcare-focused writers create professional applications for medical boards, pharmaceutical associations, and healthcare memberships—showcasing clinical expertise and patient care commitment. 🩺🏅 Medical credentials for healthcare advancement.`,
    detailedDescription: `Professional membership in healthcare organizations like medical specialty boards, pharmaceutical associations, or healthcare management bodies requires comprehensive applications demonstrating clinical competency, patient care excellence, and continuing medical education. Our specialized writers understand healthcare professional requirements and membership evaluation criteria.<br/><br/>Whether applying for medical specialty board certification, pharmaceutical industry memberships, or healthcare administration credentials, our service creates detailed applications highlighting your clinical experience, research contributions, patient outcomes, and commitment to medical excellence and patient safety.<br/><br/>Our healthcare membership applications emphasize clinical expertise, evidence-based practice, patient advocacy, and professional development, positioning you as a qualified healthcare professional committed to advancing medical knowledge and improving patient outcomes through continuous learning and professional excellence.`,
  },
  'banking-financial-services-insurance': {
    industrySubtitle: 'For Banking, Financial Services & Insurance Professionals',
    description: `<strong style="color: #2563eb;">Invest in professional recognition with sophisticated membership applications! Let our Membership Application service calculate your path to financial sector credentials! 💰📈</strong><br/><br/>Our finance-focused writers create sophisticated applications for CFA, FRM, CISA, and financial professional memberships—showcasing analytical expertise and market knowledge. 🏦🏅 Financial intelligence for professional investment.`,
    detailedDescription: `Professional membership in financial organizations like CFA Institute, Global Association of Risk Professionals (GARP), or banking professional bodies requires comprehensive applications demonstrating analytical capabilities, market expertise, and ethical commitment. Our specialized writers understand financial services professional standards and membership requirements.<br/><br/>Whether applying for CFA charterholder status, FRM certification, or banking professional memberships, our service creates detailed applications highlighting your financial analysis experience, risk management expertise, client relationship achievements, and commitment to financial industry best practices.<br/><br/>Our financial membership applications emphasize analytical rigor, ethical practice, client service excellence, and continuing education, positioning you as a qualified financial professional committed to advancing industry standards and delivering superior client outcomes through professional excellence.`,
  },
  'sales-marketing': {
    industrySubtitle: 'For Sales & Marketing Professionals',
    description: `<strong style="color: #2563eb;">Sell your professional potential with persuasive membership applications! Let our Membership Application service market your credentials for sales and marketing recognition! 📊🎯</strong><br/><br/>Our results-driven writers create compelling applications for CIM, AMA, sales professional memberships—showcasing commercial achievements and market expertise. 📈🏅 Sales excellence for professional persuasion.`,
    detailedDescription: `Professional membership in sales and marketing organizations like Chartered Institute of Marketing (CIM), American Marketing Association (AMA), or sales professional bodies requires applications demonstrating commercial success, strategic marketing expertise, and professional development. Our specialized writers understand commercial professional standards and membership evaluation criteria.<br/><br/>Whether applying for Chartered Marketer status, sales professional certifications, or marketing industry memberships, our service creates comprehensive applications highlighting your revenue achievements, campaign successes, customer relationship expertise, and contribution to commercial excellence and market innovation.<br/><br/>Our sales and marketing membership applications emphasize results achievement, strategic thinking, customer focus, and continuous learning, positioning you as a qualified commercial professional committed to driving business growth and advancing marketing and sales best practices.`,
  },
  'engineering-manufacturing': {
    industrySubtitle: 'For Engineering & Manufacturing Professionals',
    description: `<strong style="color: #2563eb;">Engineer professional excellence with precision-crafted membership applications! Let our Membership Application service manufacture your path to engineering recognition! ⚙️🏭</strong><br/><br/>Our technical writers create robust applications for IMechE, IET, ASQ, and engineering professional memberships—showcasing technical expertise and innovation achievements. 🔧🏅 Engineering precision for professional advancement.`,
    detailedDescription: `Professional membership in engineering organizations like Institution of Mechanical Engineers (IMechE), Institution of Engineering and Technology (IET), American Society for Quality (ASQ), or professional engineering bodies requires comprehensive applications demonstrating technical competency, innovative contributions, and professional responsibility. Our specialized writers understand engineering professional standards and membership requirements.<br/><br/>Whether applying for Chartered Engineer status, Professional Engineer licensure, or specialized engineering memberships, our service creates detailed applications highlighting your design projects, process improvements, technical leadership, and contribution to engineering excellence and innovation.<br/><br/>Our engineering membership applications emphasize technical innovation, professional responsibility, quality excellence, and continuing education, positioning you as a qualified engineering professional committed to advancing technical knowledge and engineering best practices through rigorous professional development.`,
  },
  'strategy-consulting': {
    industrySubtitle: 'For Strategy & Consulting Professionals',
    description: `<strong style="color: #2563eb;">Strategize professional impact with analytically precise membership applications! Let our Membership Application service consult on your path to strategic recognition! 🎯📊</strong><br/><br/>Our strategy-focused writers create analytical applications for consulting institutes, strategy associations, and business professional memberships—showcasing problem-solving expertise and client impact. 📈🏅 Strategic thinking for professional consulting.`,
    detailedDescription: `Professional membership in consulting and strategy organizations like Institute of Management Consultants, strategy professional bodies, or business analysis associations requires applications demonstrating analytical expertise, client value delivery, and professional methodology mastery. Our specialized writers understand consulting professional standards and membership evaluation criteria.<br/><br/>Whether applying for certified management consultant status, strategy professional certifications, or business consulting memberships, our service creates comprehensive applications highlighting your consulting project successes, client impact achievements, methodology expertise, and contribution to consulting excellence and business transformation.<br/><br/>Our strategy and consulting membership applications emphasize analytical rigor, client value creation, professional methodology, and ethical practice, positioning you as a qualified consulting professional committed to delivering measurable client value and advancing consulting industry standards.`,
  },
  'logistics-supply-chain': {
    industrySubtitle: 'For Logistics & Supply Chain Professionals',
    description: `<strong style="color: #2563eb;">Deliver professional excellence with operationally optimized membership applications! Let our Membership Application service optimize your path to logistics recognition! 🚚📦</strong><br/><br/>Our operations-focused writers create efficient applications for CILT, APICS, CSCMP, and supply chain professional memberships—showcasing operational expertise and efficiency achievements. ⚡🏅 Operational excellence for professional optimization.`,
    detailedDescription: `Professional membership in logistics and supply chain organizations like Chartered Institute of Logistics and Transport (CILT), APICS Supply Chain Operations Reference (SCOR), or Council of Supply Chain Management Professionals (CSCMP) requires applications demonstrating operational expertise, process optimization capabilities, and supply chain innovation. Our specialized writers understand logistics professional standards and membership requirements.<br/><br/>Whether applying for chartered logistics professional status, supply chain certifications, or transportation industry memberships, our service creates detailed applications highlighting your operational improvements, cost reduction achievements, process optimization projects, and contribution to supply chain excellence and logistics innovation.<br/><br/>Our logistics membership applications emphasize operational efficiency, strategic planning, continuous improvement, and professional development, positioning you as a qualified logistics professional committed to advancing supply chain best practices and operational excellence through systematic professional growth.`,
  },
  'hospitality-tourism': {
    industrySubtitle: 'For Hospitality & Tourism Professionals',
    description: `<strong style="color: #2563eb;">Create exceptional professional journeys with memorable membership applications! Let our Membership Application service host your path to hospitality recognition! 🏨✈️</strong><br/><br/>Our service-focused writers create welcoming applications for hospitality institutes, tourism associations, and service professional memberships—showcasing service excellence and guest experience expertise. 🌟🏅 Hospitality warmth for professional distinction.`,
    detailedDescription: `Professional membership in hospitality and tourism organizations like Institute of Hospitality, Tourism Industry Association, or hotel management professional bodies requires applications demonstrating service excellence, guest experience management, and hospitality operations expertise. Our specialized writers understand hospitality professional standards and membership evaluation criteria.<br/><br/>Whether applying for hospitality professional certifications, tourism industry memberships, or service management credentials, our service creates comprehensive applications highlighting your guest satisfaction achievements, operational excellence, cultural competency, and contribution to hospitality industry advancement and service innovation.<br/><br/>Our hospitality membership applications emphasize service excellence, guest experience focus, cultural awareness, and professional development, positioning you as a qualified hospitality professional committed to creating exceptional experiences and advancing hospitality industry standards through continuous service improvement.`,
  },
  'media-entertainment': {
    industrySubtitle: 'For Media & Entertainment Professionals',
    description: `<strong style="color: #2563eb;">Direct your professional spotlight with creatively compelling membership applications! Let our Membership Application service produce award-worthy credentials for media recognition! 🎬🎭</strong><br/><br/>Our creative writers craft captivating applications for media institutes, entertainment associations, and creative professional memberships—showcasing artistic vision and production excellence. 🎨🏅 Creative credentials for media storytelling.`,
    detailedDescription: `Professional membership in media and entertainment organizations like film industry guilds, media professional associations, or creative industry bodies requires applications demonstrating creative expertise, production capabilities, and contribution to media innovation. Our specialized writers understand creative professional standards and membership requirements.<br/><br/>Whether applying for creative industry guild memberships, media professional certifications, or entertainment industry credentials, our service creates compelling applications highlighting your creative projects, collaborative achievements, audience engagement successes, and contribution to media excellence and creative innovation.<br/><br/>Our media membership applications emphasize creative vision, collaborative excellence, audience engagement, and professional development, positioning you as a qualified media professional committed to advancing creative standards and contributing to innovative content creation in evolving entertainment landscapes.`,
  },
  'human-resources': {
    industrySubtitle: 'For Human Resources Professionals',
    description: `<strong style="color: #2563eb;">Develop exceptional professional narratives with strategic membership applications! Let our Membership Application service recruit success for your HR credentials! 👥💼</strong><br/><br/>Our people-focused writers create strategic applications for CIPD, SHRM, HR professional memberships—showcasing people expertise and organizational development achievements. 🎯🏅 People strategy for HR professional advancement.`,
    detailedDescription: `Professional membership in human resources organizations like Chartered Institute of Personnel and Development (CIPD), Society for Human Resource Management (SHRM), or HR professional bodies requires applications demonstrating people management expertise, organizational development capabilities, and strategic HR thinking. Our specialized writers understand HR professional standards and membership evaluation criteria.<br/><br/>Whether applying for chartered HR professional status, SHRM certifications, or organizational development memberships, our service creates comprehensive applications highlighting your talent management achievements, employee engagement successes, organizational change contributions, and commitment to advancing HR best practices and people development.<br/><br/>Our HR membership applications emphasize people expertise, strategic thinking, ethical practice, and professional development, positioning you as a qualified HR professional committed to driving organizational success through effective people management and advancing human resources professional standards.`,
  },
  'fmcg-retail': {
    industrySubtitle: 'For FMCG & Retail Professionals',
    description: `<strong style="color: #2563eb;">Stock your professional future with market-ready membership applications! Let our Membership Application service retail your credentials for FMCG recognition! 🛒🏪</strong><br/><br/>Our consumer-focused writers create compelling applications for retail institutes, FMCG associations, and commercial professional memberships—showcasing market expertise and consumer insight. 📊🏅 Consumer intelligence for retail professional advancement.`,
    detailedDescription: `Professional membership in FMCG and retail organizations like Institute of Grocery Distribution, retail professional bodies, or consumer goods associations requires applications demonstrating commercial expertise, consumer understanding, and market innovation capabilities. Our specialized writers understand commercial professional standards and membership requirements.<br/><br/>Whether applying for retail professional certifications, FMCG industry memberships, or commercial strategy credentials, our service creates detailed applications highlighting your brand management achievements, market expansion successes, consumer engagement innovations, and contribution to retail excellence and commercial best practices.<br/><br/>Our FMCG and retail membership applications emphasize market insight, consumer focus, commercial results, and professional development, positioning you as a qualified commercial professional committed to advancing retail standards and contributing to consumer market innovation and commercial excellence.`,
  },
  'legal-compliance': {
    industrySubtitle: 'For Legal & Compliance Professionals',
    description: `<strong style="color: #2563eb;">Build compelling professional cases with authoritative membership applications! Let our Membership Application service advocate for your legal credentials! ⚖️📋</strong><br/><br/>Our legally-focused writers create authoritative applications for bar associations, compliance institutes, and legal professional memberships—showcasing legal expertise and regulatory excellence. 🏛️🏅 Legal authority for professional advocacy.`,
    detailedDescription: `Professional membership in legal and compliance organizations like bar associations, compliance professional bodies, or legal specialization boards requires comprehensive applications demonstrating legal expertise, ethical commitment, and professional competency. Our specialized writers understand legal professional standards and membership evaluation criteria.<br/><br/>Whether applying for bar admission, compliance professional certifications, or legal specialization credentials, our service creates detailed applications highlighting your legal achievements, case management experience, regulatory expertise, and commitment to legal excellence and professional responsibility.<br/><br/>Our legal membership applications emphasize legal competency, ethical practice, professional responsibility, and continuing education, positioning you as a qualified legal professional committed to advancing legal standards and delivering expert legal counsel through rigorous professional development and ethical practice.`,
  },
  'public-sector-government': {
    industrySubtitle: 'For Public Sector & Government Professionals',
    description: `<strong style="color: #2563eb;">Serve professional distinction with impactful membership applications! Let our Membership Application service govern your path to public sector recognition! 🏛️🌟</strong><br/><br/>Our public service-focused writers create impactful applications for public administration institutes, government professional memberships—showcasing civic commitment and policy expertise. 📋🏅 Civic duty for public professional advancement.`,
    detailedDescription: `Professional membership in public sector and government organizations like public administration institutes, policy professional bodies, or government management associations requires applications demonstrating public service commitment, policy expertise, and administrative excellence. Our specialized writers understand public sector professional standards and membership requirements.<br/><br/>Whether applying for public administration certifications, policy professional memberships, or government management credentials, our service creates comprehensive applications highlighting your policy development achievements, program management successes, stakeholder engagement excellence, and commitment to effective governance and public service innovation.<br/><br/>Our public sector membership applications emphasize public service commitment, policy expertise, stakeholder engagement, and professional development, positioning you as a qualified public service professional committed to advancing governance standards and contributing to effective public administration and community service excellence.`,
  },
  'chemicals-materials': {
    industrySubtitle: 'For Chemicals & Materials Professionals',
    description: `<strong style="color: #2563eb;">Formulate professional success with scientifically precise membership applications! Let our Membership Application service engineer compelling credentials for chemicals and materials recognition! ⚗️🧪</strong><br/><br/>Our science-focused writers create precise applications for chemical institutes, materials societies, and scientific professional memberships—showcasing research excellence and innovation achievements. 🔬🏅 Scientific credentials for professional formulation.`,
    detailedDescription: `Professional membership in chemicals and materials organizations like Royal Society of Chemistry, Materials Research Society, or chemical engineering professional bodies requires comprehensive applications demonstrating technical expertise, research contributions, and scientific innovation. Our specialized writers understand scientific professional standards and membership evaluation criteria.<br/><br/>Whether applying for chartered chemist status, materials science professional certifications, or chemical engineering memberships, our service creates detailed applications highlighting your research achievements, technical innovations, publication records, and contribution to advancing chemical and materials science knowledge and industrial applications.<br/><br/>Our chemicals and materials membership applications emphasize scientific rigor, research excellence, technical innovation, and professional development, positioning you as a qualified scientific professional committed to advancing chemical and materials science through rigorous research and contributing to technological innovation and scientific knowledge advancement.`,
  },
}

const MembershipApplicationPageContent = () => {
  const searchParams = useSearchParams()
  const industry = searchParams.get('industry')

  const industryContent =
    industry && industrySpecificContent[industry as keyof typeof industrySpecificContent]

  const serviceData = {
    ...servicesData.membershipApplication,
    service: {
      ...servicesData.membershipApplication.service,
      ...(industryContent && {
        description: industryContent.description,
        detailedDescription: industryContent.detailedDescription,
      }),
    },
    ...(industryContent && {
      industrySubtitle: industryContent.industrySubtitle,
    }),
  }

  return <ServiceProductPage {...serviceData} />
}

export default MembershipApplicationPageContent
