'use client'

import { useSearchParams } from 'next/navigation'
import ServiceProductPage from '../ServiceProductPage'
import { servicesData } from '@/data/servicesData'

// Industry-specific content for Project Portfolio Services
const industrySpecificContent = {
  'construction-industry': {
    industrySubtitle: 'For Construction Industry Professionals',
    description: `<strong style="color: #2563eb;">Build an impressive project showcase! Let our Project Portfolio service construct compelling presentations of your construction achievements! 🏗️📂</strong><br/><br/>Our construction-focused designers create powerful portfolios for architects, engineers, and project managers—showcasing technical projects and construction expertise. 🚧✨ Professional project blueprints for construction success.`,
    detailedDescription: `In the construction industry, your project portfolio is crucial for demonstrating technical competency, project management skills, and construction achievements. Our specialized team creates comprehensive portfolios that showcase your most impressive construction projects, from residential developments to large-scale commercial and infrastructure projects.<br/><br/>Whether you're an Architect, Civil Engineer, Construction Project Manager, or Structural Engineer, our portfolios highlight your technical drawings, project photographs, construction methodologies, budget management, and successful project completions. We present your projects with professional layouts that emphasize safety achievements, on-time delivery, budget adherence, and innovative construction solutions.<br/><br/>Our construction portfolios include detailed project descriptions, technical specifications, construction challenges overcome, team leadership examples, and quantified achievements such as cost savings, schedule improvements, and safety record enhancements. Perfect for showcasing your expertise to potential employers, clients, or for professional certification requirements, our portfolios position you as a results-driven construction professional with proven project delivery capabilities.`,
  },
  'energy-oil-gas': {
    industrySubtitle: 'For Energy, Oil & Gas Professionals',
    description: `<strong style="color: #2563eb;">Power your career with dynamic project presentations! Let our Project Portfolio service fuel compelling showcases of your energy sector achievements! ⚡🛢️</strong><br/><br/>Our energy-focused team creates impactful portfolios for petroleum engineers, renewable energy specialists, and operations managers—showcasing technical projects and industry expertise. 🏭📂 Professional energy for project advancement.`,
    detailedDescription: `Energy sector professionals need portfolios that demonstrate technical expertise, operational achievements, and contribution to energy project success. Our specialized team creates comprehensive portfolios showcasing your involvement in upstream exploration, downstream processing, renewable energy installations, or energy efficiency projects.<br/><br/>Whether you're in Oil & Gas Operations, Renewable Energy Development, Process Engineering, or Environmental Compliance, our portfolios highlight your technical contributions, operational improvements, safety enhancements, and project delivery successes. We present complex energy projects with clear technical explanations and quantified results.<br/><br/>Our energy portfolios emphasize achievements such as production optimization, cost reduction, environmental impact mitigation, and successful technology implementation, positioning you as a technical leader ready to drive energy sector innovation and operational excellence.`,
  },
  'tech-it': {
    industrySubtitle: 'For Technology & IT Professionals',
    description: `<strong style="color: #2563eb;">Debug your career potential with cutting-edge project showcases! Let our Project Portfolio service code compelling presentations of your tech achievements! 💻🚀</strong><br/><br/>Our tech-savvy team develops innovative portfolios for software engineers, data scientists, and IT managers—showcasing technical projects and digital innovation. 🔧📂 Digital portfolios engineered for tech success.`,
    detailedDescription: `Technology professionals need portfolios that demonstrate coding expertise, system architecture knowledge, and successful project delivery. Our specialized team creates comprehensive portfolios showcasing your software development projects, system implementations, data science analyses, or IT infrastructure achievements.<br/><br/>Whether you're a Software Developer, Data Scientist, DevOps Engineer, or IT Manager, our portfolios highlight your technical skills, programming languages, frameworks used, and project outcomes. We present complex technical projects with clear explanations accessible to both technical and non-technical audiences.<br/><br/>Our tech portfolios include code samples, system diagrams, user interfaces, performance metrics, and quantified results such as application performance improvements, user adoption rates, and system efficiency gains, positioning you as a technical innovator ready to drive digital transformation.`,
  },
  'healthcare-pharma': {
    industrySubtitle: 'For Healthcare & Pharmaceutical Professionals',
    description: `<strong style="color: #2563eb;">Prescribe professional excellence with compelling project presentations! Let our Project Portfolio service diagnose your path to healthcare achievement showcases! 🏥💊</strong><br/><br/>Our healthcare-focused team creates professional portfolios for medical professionals, pharmaceutical specialists, and healthcare administrators—showcasing clinical projects and healthcare innovation. 🩺📂 Medical portfolios for healthcare advancement.`,
    detailedDescription: `Healthcare and pharmaceutical professionals need portfolios that demonstrate clinical expertise, research contributions, and commitment to patient outcomes. Our specialized team creates comprehensive portfolios showcasing your clinical research projects, quality improvement initiatives, pharmaceutical development work, or healthcare administration achievements.<br/><br/>Whether you're in Clinical Research, Pharmaceutical Development, Healthcare Quality Improvement, or Medical Device Innovation, our portfolios highlight your research methodologies, clinical outcomes, regulatory compliance, and contribution to advancing healthcare quality. We present complex medical projects with clear clinical significance and patient impact.<br/><br/>Our healthcare portfolios emphasize achievements such as improved patient outcomes, research publication contributions, regulatory approval successes, and quality improvement metrics, positioning you as a healthcare professional committed to advancing medical knowledge and patient care excellence.`,
  },
  'banking-financial-services-insurance': {
    industrySubtitle: 'For Banking, Financial Services & Insurance Professionals',
    description: `<strong style="color: #2563eb;">Invest in portfolio excellence with sophisticated project presentations! Let our Project Portfolio service calculate compelling showcases of your financial achievements! 💰📈</strong><br/><br/>Our finance-focused team creates sophisticated portfolios for investment professionals, financial analysts, and insurance specialists—showcasing analytical projects and market expertise. 🏦📂 Financial intelligence for portfolio investment.`,
    detailedDescription: `Financial services professionals need portfolios that demonstrate analytical capabilities, market expertise, and successful project delivery. Our specialized team creates comprehensive portfolios showcasing your financial analysis projects, investment strategies, risk management initiatives, or client relationship achievements.<br/><br/>Whether you're in Investment Banking, Financial Planning, Risk Management, or Insurance Services, our portfolios highlight your analytical methodologies, financial models, client results, and contribution to business growth. We present complex financial projects with clear business impact and quantified outcomes.<br/><br/>Our financial portfolios emphasize achievements such as portfolio performance improvements, risk reduction metrics, client satisfaction enhancements, and revenue generation results, positioning you as a financial professional ready to drive results in competitive markets.`,
  },
  'sales-marketing': {
    industrySubtitle: 'For Sales & Marketing Professionals',
    description: `<strong style="color: #2563eb;">Sell your success with persuasive project presentations! Let our Project Portfolio service market compelling showcases of your commercial achievements! 📊🎯</strong><br/><br/>Our results-driven team creates compelling portfolios for sales executives, marketing managers, and business development professionals—showcasing commercial projects and market success. 📈📂 Sales excellence for portfolio persuasion.`,
    detailedDescription: `Sales and marketing professionals need portfolios that demonstrate commercial achievements, campaign successes, and revenue generation capabilities. Our specialized team creates comprehensive portfolios showcasing your sales campaigns, marketing initiatives, business development projects, or client acquisition achievements.<br/><br/>Whether you're in B2B Sales, Digital Marketing, Brand Management, or Business Development, our portfolios highlight your campaign strategies, sales methodologies, customer insights, and quantified business results. We present commercial projects with clear ROI demonstrations and market impact.<br/><br/>Our sales and marketing portfolios emphasize achievements such as revenue growth, lead generation improvements, customer acquisition rates, and market expansion successes, positioning you as a commercial professional ready to drive business growth and market success.`,
  },
  'engineering-manufacturing': {
    industrySubtitle: 'For Engineering & Manufacturing Professionals',
    description: `<strong style="color: #2563eb;">Engineer portfolio excellence with precision-crafted project showcases! Let our Project Portfolio service manufacture compelling presentations of your technical achievements! ⚙️🏭</strong><br/><br/>Our technical team creates robust portfolios for mechanical engineers, manufacturing managers, and quality specialists—showcasing engineering projects and operational excellence. 🔧📂 Engineering precision for portfolio advancement.`,
    detailedDescription: `Engineering and manufacturing professionals need portfolios that demonstrate technical expertise, problem-solving capabilities, and operational improvements. Our specialized team creates comprehensive portfolios showcasing your design projects, process improvements, manufacturing optimizations, or quality enhancement initiatives.<br/><br/>Whether you're in Product Design, Process Engineering, Manufacturing Operations, or Quality Assurance, our portfolios highlight your technical methodologies, engineering solutions, process improvements, and quantified operational results. We present complex engineering projects with clear technical explanations and business impact.<br/><br/>Our engineering portfolios emphasize achievements such as cost reduction, efficiency improvements, quality enhancements, and successful project delivery, positioning you as an engineering professional ready to drive technical innovation and operational excellence.`,
  },
  'strategy-consulting': {
    industrySubtitle: 'For Strategy & Consulting Professionals',
    description: `<strong style="color: #2563eb;">Strategize portfolio impact with analytically precise project presentations! Let our Project Portfolio service consult on compelling showcases of your strategic achievements! 🎯📊</strong><br/><br/>Our strategy-focused team creates analytical portfolios for management consultants, strategy advisors, and business analysts—showcasing strategic projects and consulting excellence. 📈📂 Strategic thinking for portfolio consulting.`,
    detailedDescription: `Strategy and consulting professionals need portfolios that demonstrate analytical thinking, problem-solving methodologies, and client impact. Our specialized team creates comprehensive portfolios showcasing your consulting projects, strategic analyses, organizational transformation initiatives, or business improvement achievements.<br/><br/>Whether you're in Management Consulting, Strategy Development, Business Analysis, or Change Management, our portfolios highlight your analytical frameworks, strategic recommendations, implementation results, and client value delivery. We present complex business projects with clear methodologies and quantified outcomes.<br/><br/>Our consulting portfolios emphasize achievements such as cost savings generated, revenue improvements, process efficiency gains, and successful transformation initiatives, positioning you as a strategic professional ready to drive business excellence and organizational success.`,
  },
  'logistics-supply-chain': {
    industrySubtitle: 'For Logistics & Supply Chain Professionals',
    description: `<strong style="color: #2563eb;">Deliver portfolio excellence with operationally optimized project showcases! Let our Project Portfolio service optimize compelling presentations of your logistics achievements! 🚚📦</strong><br/><br/>Our operations-focused team creates efficient portfolios for supply chain managers, logistics coordinators, and procurement specialists—showcasing operational projects and strategic vision. ⚡📂 Operational excellence for portfolio optimization.`,
    detailedDescription: `Logistics and supply chain professionals need portfolios that demonstrate operational expertise, process optimization capabilities, and supply chain improvements. Our specialized team creates comprehensive portfolios showcasing your supply chain optimization projects, logistics coordination achievements, procurement improvements, or distribution enhancements.<br/><br/>Whether you're in Supply Chain Management, Logistics Operations, Procurement, or Distribution, our portfolios highlight your operational methodologies, process improvements, vendor management successes, and quantified efficiency results. We present complex logistics projects with clear operational impact and cost benefits.<br/><br/>Our logistics portfolios emphasize achievements such as cost reduction, delivery time improvements, inventory optimization, and supplier relationship enhancements, positioning you as an operations professional ready to drive supply chain excellence and logistical innovation.`,
  },
  'hospitality-tourism': {
    industrySubtitle: 'For Hospitality & Tourism Professionals',
    description: `<strong style="color: #2563eb;">Create exceptional portfolio experiences with memorable project showcases! Let our Project Portfolio service host compelling presentations of your hospitality achievements! 🏨✈️</strong><br/><br/>Our service-focused team creates welcoming portfolios for hotel managers, tourism specialists, and event coordinators—showcasing service projects and guest experience excellence. 🌟📂 Hospitality warmth for portfolio distinction.`,
    detailedDescription: `Hospitality and tourism professionals need portfolios that demonstrate service excellence, event management capabilities, and guest experience achievements. Our specialized team creates comprehensive portfolios showcasing your hospitality projects, event coordination successes, tourism development initiatives, or guest service improvements.<br/><br/>Whether you're in Hotel Management, Event Planning, Tourism Development, or Guest Services, our portfolios highlight your service methodologies, guest satisfaction improvements, event execution excellence, and operational achievements. We present hospitality projects with emphasis on guest experience and service quality.<br/><br/>Our hospitality portfolios emphasize achievements such as guest satisfaction scores, revenue growth, event success metrics, and operational efficiency improvements, positioning you as a hospitality professional committed to creating exceptional experiences and service excellence.`,
  },
  'media-entertainment': {
    industrySubtitle: 'For Media & Entertainment Professionals',
    description: `<strong style="color: #2563eb;">Direct your portfolio spotlight with creatively compelling project showcases! Let our Project Portfolio service produce award-worthy presentations of your media achievements! 🎬🎭</strong><br/><br/>Our creative team crafts captivating portfolios for content creators, producers, and media professionals—showcasing creative projects and entertainment excellence. 🎨📂 Creative portfolios for media storytelling.`,
    detailedDescription: `Media and entertainment professionals need portfolios that demonstrate creative capabilities, technical expertise, and successful content creation. Our specialized team creates comprehensive portfolios showcasing your media production projects, content creation achievements, creative collaborations, or entertainment industry contributions.<br/><br/>Whether you're in Film Production, Content Creation, Media Marketing, or Entertainment Management, our portfolios highlight your creative processes, technical skills, audience engagement results, and artistic achievements. We present creative projects with visual impact and measurable success metrics.<br/><br/>Our media portfolios emphasize achievements such as audience growth, content performance metrics, creative recognition, and successful project delivery, positioning you as a media professional ready to create compelling content and drive creative innovation.`,
  },
  'human-resources': {
    industrySubtitle: 'For Human Resources Professionals',
    description: `<strong style="color: #2563eb;">Develop exceptional portfolio narratives with strategic project showcases! Let our Project Portfolio service recruit success for your HR achievement presentations! 👥💼</strong><br/><br/>Our people-focused team creates strategic portfolios for HR managers, talent acquisition specialists, and organizational development professionals—showcasing people projects and strategic vision. 🎯📂 People strategy for HR portfolio advancement.`,
    detailedDescription: `Human resources professionals need portfolios that demonstrate people management expertise, organizational development capabilities, and HR program successes. Our specialized team creates comprehensive portfolios showcasing your HR initiatives, talent development projects, organizational change programs, or employee engagement achievements.<br/><br/>Whether you're in Talent Acquisition, Employee Relations, Training & Development, or HR Strategy, our portfolios highlight your HR methodologies, program outcomes, employee satisfaction improvements, and organizational impact. We present HR projects with clear business alignment and people-focused results.<br/><br/>Our HR portfolios emphasize achievements such as employee retention improvements, training program effectiveness, recruitment efficiency gains, and organizational culture enhancements, positioning you as an HR professional ready to drive organizational success through effective people management.`,
  },
  'fmcg-retail': {
    industrySubtitle: 'For FMCG & Retail Professionals',
    description: `<strong style="color: #2563eb;">Stock your portfolio with market-ready project showcases! Let our Project Portfolio service retail compelling presentations of your commercial achievements! 🛒🏪</strong><br/><br/>Our consumer-focused team creates compelling portfolios for brand managers, retail buyers, and category specialists—showcasing commercial projects and consumer expertise. 📊📂 Consumer intelligence for retail portfolio advancement.`,
    detailedDescription: `FMCG and retail professionals need portfolios that demonstrate commercial expertise, brand management capabilities, and market success. Our specialized team creates comprehensive portfolios showcasing your brand campaigns, retail initiatives, product launches, or category management achievements.<br/><br/>Whether you're in Brand Management, Category Management, Retail Operations, or Consumer Marketing, our portfolios highlight your commercial strategies, consumer insights, market analysis, and business results. We present commercial projects with clear market impact and quantified outcomes.<br/><br/>Our FMCG and retail portfolios emphasize achievements such as sales growth, market share gains, product launch successes, and consumer engagement improvements, positioning you as a commercial professional ready to drive market success and retail innovation.`,
  },
  'legal-compliance': {
    industrySubtitle: 'For Legal & Compliance Professionals',
    description: `<strong style="color: #2563eb;">Build compelling portfolio cases with authoritative project showcases! Let our Project Portfolio service advocate for your legal achievement presentations! ⚖️📋</strong><br/><br/>Our legally-focused team creates authoritative portfolios for attorneys, compliance officers, and legal analysts—showcasing legal projects and compliance excellence. 🏛️📂 Legal authority for portfolio advocacy.`,
    detailedDescription: `Legal and compliance professionals need portfolios that demonstrate legal expertise, regulatory knowledge, and successful case management. Our specialized team creates comprehensive portfolios showcasing your legal cases, compliance programs, regulatory projects, or risk management initiatives.<br/><br/>Whether you're in Corporate Law, Compliance Management, Legal Analysis, or Risk Management, our portfolios highlight your legal methodologies, case outcomes, compliance achievements, and regulatory expertise. We present legal projects with clear business impact and risk mitigation results.<br/><br/>Our legal portfolios emphasize achievements such as successful case resolutions, compliance program effectiveness, risk reduction metrics, and regulatory approval successes, positioning you as a legal professional ready to provide expert counsel and drive organizational compliance excellence.`,
  },
  'public-sector-government': {
    industrySubtitle: 'For Public Sector & Government Professionals',
    description: `<strong style="color: #2563eb;">Serve with portfolio distinction through impactful project showcases! Let our Project Portfolio service govern compelling presentations of your public service achievements! 🏛️🌟</strong><br/><br/>Our public service-focused team creates impactful portfolios for government officials, policy analysts, and public administrators—showcasing civic projects and public service excellence. 📋📂 Civic duty for public portfolio advancement.`,
    detailedDescription: `Public sector and government professionals need portfolios that demonstrate public service commitment, policy expertise, and community impact. Our specialized team creates comprehensive portfolios showcasing your policy development projects, public administration initiatives, community programs, or government service achievements.<br/><br/>Whether you're in Policy Development, Public Administration, Program Management, or Community Engagement, our portfolios highlight your public service methodologies, policy outcomes, program effectiveness, and community impact. We present public sector projects with clear civic value and measurable benefits.<br/><br/>Our public sector portfolios emphasize achievements such as policy implementation success, program efficiency improvements, stakeholder engagement results, and community impact metrics, positioning you as a public service professional committed to effective governance and positive community outcomes.`,
  },
  'chemicals-materials': {
    industrySubtitle: 'For Chemicals & Materials Professionals',
    description: `<strong style="color: #2563eb;">Formulate portfolio success with scientifically precise project showcases! Let our Project Portfolio service engineer compelling presentations of your technical achievements! ⚗️🧪</strong><br/><br/>Our science-focused team creates precise portfolios for research scientists, process engineers, and materials specialists—showcasing technical projects and innovation excellence. 🔬📂 Scientific portfolios for career formulation.`,
    detailedDescription: `Chemicals and materials professionals need portfolios that demonstrate technical expertise, research capabilities, and innovation contributions. Our specialized team creates comprehensive portfolios showcasing your research projects, process development work, materials innovation, or quality improvement initiatives.<br/><br/>Whether you're in R&D, Process Engineering, Quality Control, or Product Development, our portfolios highlight your research methodologies, technical innovations, process improvements, and scientific achievements. We present complex technical projects with clear commercial applications and quantified results.<br/><br/>Our chemicals and materials portfolios emphasize achievements such as process efficiency improvements, product development successes, quality enhancements, and research publication contributions, positioning you as a technical professional ready to drive scientific innovation and technological advancement.`,
  },
}

const ProjectPortfolioPageContent = () => {
  const searchParams = useSearchParams()
  const industry = searchParams.get('industry')

  const industryContent =
    industry && industrySpecificContent[industry as keyof typeof industrySpecificContent]

  const serviceData = {
    ...servicesData.projectPortfolio,
    service: {
      ...servicesData.projectPortfolio.service,
      ...(industryContent && {
        description: industryContent.description,
        detailedDescription: industryContent.detailedDescription,
      }),
    },
    ...(industryContent && {
      industrySubtitle: industryContent.industrySubtitle,
    }),
  }

  return <ServiceProductPage {...serviceData} />
}

export default ProjectPortfolioPageContent
